kudobuilder/kudo

Makefile
config/default/manager_image_patch.yaml
config/default/manager_image_patch.yaml-e
config/rbac/rbac_role.yaml
pkg/controller/framework/framework_controller_test.go
pkg/controller/frameworkversion/frameworkversion_controller_test.go
pkg/controller/instance/instance_controller_test.go
pkg/controller/planexecution/planexecution_controller.go
pkg/controller/planexecution/planexecution_controller_test.go

This branch was used to push the 0.2.0 docker image to the registry.
There were also fixes on this branch to allow the Image to be used on the clsuter to manage the objects.   Its a manual process right now for adding support for specific image types.  I'm of two minds:
1) Just add everything now - easy, nothing to worry about
2) Add them one by one to make sure the IsHealthy() function handles them correctly.  If someone adds support for something its on them to make sure they properly capture the healthcheck for that object type.
Works on #52 . and #51.  We need to go back and deploy 0.1.0, but that requires fixing the tests on that tag, or manually running the commands

Docker build

---

README.md

For Documentation purposes I added:
- Added `Getting Started` section in `readme.md` to demonstrate `Zookeeper` and `Kafka` operators
- Created `docs/gif` and added the `quickstart-0.1.0.gif`

Added quick start video

---

config/samples/mysql.yaml
docs/Backups.md
pkg/controller/planexecution/planexecution_controller.go
pkg/util/health/ready.go

This outlines an example application that defines how to backup and restore data within the application definition.
Could you guys please review for 
1) Working docs and how to run them.  Happy to expand where is interesting
2) Format of tasks.  Would like to convert this to use a base job.yaml spec with a patch that changes the command run in the job.
3) Is this the right app (Redis, kafka, zookeeper, etc)?

Added example MYSQL framework with backup and restore tasks

---

cmd/kubectl-plugin/kubectl-maestro
config/crds/maestro_v1alpha1_frameworkversion.yaml
config/crds/maestro_v1alpha1_instance.yaml
config/rbac/rbac_role.yaml
config/samples/canary.yaml
config/samples/flink-demo.yaml
config/samples/flink-demo/Dockerfile
config/samples/flink-demo/upload.sh
config/samples/flink.yaml
config/samples/kubectl-maestro
config/samples/zookeeper-frameworkversion.yaml
config/scratch/mysql-backup.yaml
config/scratch/mysql-restore.yaml
config/scratch/validation.yaml
docs/ApplicationUpgrades.md
docs/CLIUsage.md
docs/DeleteObjectTasks.md
docs/Flink.md
pkg/apis/maestro/v1alpha1/instance_types.go
pkg/controller/instance/instance_controller.go
pkg/controller/planexecution/planexecution_controller.go
pkg/util/health/ready.go

This is a WIP.
Usage in combination with Flink, see this video https://cl.ly/2988619f8474
Add `kubectl-maestro` to your `$PATH`.
|  Syntax | Description  | 
|---|---|
| kubectl maestro install something  |  Lists all available frameworks from the `Maestro App Store` that can be installed | 
| kubectl maestro install <frameworkName>  |  Installs a framework from the `Maestro App Store` with dependencies | 
| kubectl maestro uninstall <frameworkName> | Uninstalls a framework with all dependencies | 
| kubectl maestro shell |  Lists all available frameworks of which you could get a shell  | 
| kubectl maestro shell <frameworkName> |  gives you a shell - right now just Flink supported | 
| kubectl maestro exec <frameworkName>  <cmd>|  Executes a command for a particular framework - right now …

[WIP] Kubectl Maestro Plugin

---

pkg/controller/framework/framework_controller.go
pkg/controller/frameworkversion/frameworkversion_controller.go
pkg/controller/instance/instance_controller.go
pkg/controller/planexecution/planexecution_controller.go
pkg/util/health/ready.go

Intended to have the logs more human readible but also educating the user for the flow. This is especially beneficial when troubleshooting.

Log Message Improvement for Maestro

---

config/samples/mysql.yaml
pkg/apis/maestro/v1alpha1/frameworkversion_types.go
pkg/controller/instance/instance_controller.go

```bash
$kubectl apply -f config/samples/mysql.yaml
framework.maestro.k8s.io/mysql created
frameworkversion.maestro.k8s.io/mysql-57 created
instance.maestro.k8s.io/mysql created
$kubectl get planexecutions
NAME                     AGE
mysql-deploy-300930000   13s
$k get pods
NAME                           READY   STATUS      RESTARTS   AGE
mysql-deploy-job-95k6r         0/1     Completed   0          5s
mysql-mysql-864c69cf97-5xfbw   1/1     Running     0          31s
$ kubectl patch instance mysql -p '{"spec":{"parameters":{"BACKUP_FILE":"new-backup.sql"}}}' --type=merge
instance.maestro.k8s.io/mysql patched
$ kubectl get planexecutions
NAME                     AGE
mysql-backup-690459000   7s
mysql-deploy-300930000   1m
```

Created ability to trigger specific plans when parameters change

---

CONTRIBUTING.md
keps/0000-kep-template.md

This is a work-in-progress, please iterate on it. It relates to/blocks #99.

[WIP] Adding KEP template

---

docs/Backups.md
keps/0000-kep-template.md
keps/0001-kep-process.md
keps/draft-0001-kep-process.md

Draft of the KUDO Enhancement Proposal Process inspired by https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md
This is also needed for https://github.com/kudobuilder/kudo/issues/99
Once we achieve agreement we should:
* Change the `kep-number` from `kep-number: draft-20190214` to `kep-number: 1`
* Change the status to `implemented`
* Rename the file from `draft-0001-kep-process.md` to `0001-kep-process.md`

drafted 0001-kep-proccess.md

---

keps/0001-kep-process.md

This is an update for `kep-1` to reflect the creation of a milestone once the status of a KEP changes from `provisional` to `implementable`. It should help to avoid label growth and to organize proposed features via milestones.

[KEP 0001] KUDO Enhancement Proposal Process - Update

---

CONTRIBUTING.md
Makefile
README.md
RELEASE.md
keps/draft-0003-kep-cli.md

[KEP 0003] Initial Draft for 0003-kep-cli.md

---

keps/0000-kep-template.md

This should make the developer experience easier by following a simple naming convention when doing PRs for KEPs.

[KEP 0000] Added PR naming convention to template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement-request.md

I propose two issue templates that should cover most cases I can think of right now:
- Bug reports
- Enhancement Requests
Feature requests would imo be Enhancement Requests as the current flow would be to create a kep out of it.
The ISSUE_TEMPLATES were created with the issue builder inspired by https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE
This references also https://github.com/kudobuilder/kudo/issues/113

Update to issue templates

---

pkg/util/health/ready.go

/component operator
Right now the log output of KUDO shows the entire passed StatefulSet object printed to stdout which makes it hard to read through logs.
Fixes #140
```release-note
```

Fixing HealthUtil StatefulSet Log Output

---

Dockerfile

/kind cleanup
Prevents building Docker Image from a `:latest` tag
Fixes #
```release-note
None
```

Removed ubuntu:latest and fixed tag to 18.04

---

docs/cli.md
docs/examples/apache-zookeeper.md

Fix markdown tables on the website, make example commands consistent.

---

README.md
docs/cli.md

Making sure users using a version of kubectl that supports plugin features needed for our CLI.
Fixes #
Fixes https://kubernetes.slack.com/archives/CG3HTFCMV/p1554919242069900
```release-note
NONE
```

Adding kubectl version 1.12 to pre-requisites

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/install/install_test.go
pkg/kudoctl/util/check/check.go
pkg/kudoctl/util/check/check_test.go
pkg/kudoctl/util/github/client.go
pkg/kudoctl/util/github/client_test.go
pkg/kudoctl/util/github/credential.go
pkg/kudoctl/util/github/credential_test.go
pkg/kudoctl/util/helpers/helpers.go
pkg/kudoctl/util/helpers/helpers_test.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go
test/formatting.sh

The format checking script was advertising /bin/sh instead of /bin/bash while it was using features not available in bourne shell. By changing the shebang the build finally started failing and because of that this PR also includes formatting fixes.

Fix the formatting script

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/install/install_test.go
pkg/kudoctl/cmd/install_test.go
pkg/kudoctl/cmd/root.go
pkg/kudoctl/util/check/check.go
pkg/kudoctl/util/github/client.go
pkg/kudoctl/util/github/client_test.go
pkg/kudoctl/util/helpers/helpers.go
pkg/kudoctl/util/helpers/helpers_test.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go

/kind cleanup
* Linter is happy and who does not like a happy linter.   
* Some cleanup on function names as well.
Fixes #
The function passed as `RunE` to Cobra took some digging into.  Function name and dependent functions names were changed to reflect their purpose.  It is the only non-linter change.
```release-note
NONE
```

Happy Linter!!

---

Makefile
STYLEGUIDE.md

Starts a coding style guide
Fixes #
It is expected that this is a living document.   It doesn't make sense to capture all possible cases upfront.  however, as we get and give PR feedback, cases needing clarification should be added here.
```release-note
NONE
```

Starting a coding style guide

---

Makefile
config/crds/kudo_v1alpha1_instance.yaml
config/crds/kudo_v1alpha1_planexecution.yaml

/component generator
/kind cleanup
* The move of `config/rbac` under `config/default` to fix kustomize was incomplete.  These are generated files.  This PR fixes the generation to be correct.   There are some additional generated files that came along for the ride.
Fixes #
```release-note
NONE
```

Configure manifest generation to the correct directory

---

keps/0006-stable-kafka-example.md

>
> /kind bug
> /kind design
> /kind kep
Fixes #
```release-note
```

Adding a user story

---

config/crds/kudo_v1alpha1_framework.yaml
config/crds/kudo_v1alpha1_frameworkversion.yaml
config/crds/kudo_v1alpha1_instance.yaml
config/crds/kudo_v1alpha1_planexecution.yaml
pkg/apis/kudo/v1alpha1/framework_types.go
pkg/apis/kudo/v1alpha1/frameworkversion_types.go
pkg/apis/kudo/v1alpha1/instance_types.go
pkg/apis/kudo/v1alpha1/planexecution_types.go

These were originally reported by staticcheck, but staticcheck master has been fixed to account for openapi-gen mis-using the `json` struct tags.

Fix inline JSON struct tags

---

docs/Comparison.md

@gerred @joerg84 
This is something I'm going to keep working on over the next few days, but wanted to have this here to comment on.

Comparion between tools

---

pkg/kudoctl/cmd/version.go

/kind cleanup
passes the static checks
Fixes #
```release-note
NONE
```

make check-formatting failures fixed

---

.gitignore
Makefile
hack/update_codegen.sh
hack/update_manifests.sh

/component generator
/kind cleanup
Caching code-gen tools.  This will enable:
1) faster dev cycles
2) ability to use the tools while disconnected from net (airplane ride)
Fixes #
```release-note
NONE
```

caching tools for code gens

---

keps/draft-20190418-skeleton-generator.md

/kind kep
Having a Skeleton generator would help people getting started faster when they want to develop a new KUDO framework.
Fixes #
```release-note
```

Adding the kep for the skeleton generator

---

keps/0004-add-testing-infrastructure.md
pkg/apis/kudo/v1alpha1/framework_types.go
pkg/controller/frameworkversion/frameworkversion_controller.go
pkg/controller/instance/instance_controller.go
pkg/controller/planexecution/planexecution_controller.go

/kind cleanup
* removing left behind scaffold todos 
* fixing misspelling
* added error handling where it was missing
Fixes #
```release-note
NONE
```

removing left behind scaffold todos and fixing misspelling

---

.github/ISSUE_TEMPLATE/bug_report.md

This is a small and quick fix to something I just noticed today. The provided command to post the KUDO version when filing bug reports inherited an old name. The  command via the CLI should refer to `kubectl kudo version` and not `kubectl kudoctl version`. If someone would copy&paste the current instructions, it simply wouldn't work. This PR fixes this.
Fixes #
```release-note
NONE
```

Update bug_report.md to fix

---

docs/cli.md
docs/faq.md
docs/usage.md

This contains some minor edits for readability of documentation, as well as a couple typo fixes.
I'm not sure an issue is warranted.
Some of the docs pages are pretty inconsistent with respect to addressing the reader: they use "you can do X" or "here we see Y" arbitrarily. I'd love to converge towards "you", addressing the reader directly. Let me know if I can take on this effort as well.
NONE

minor documentation edits and typo fixes

---

docs/getting-started.md

A minor fix which amends the link to the Kafka example in the 'getting started' section, as it's likely newcomers would stumble on this page.
```release-note
NONE
```

Fix broken link to Kafka example in 'getting started' section

---

config/samples/kafka-instance.yaml
docs/getting-started.md

Complicated application stacks and their lifecycles require more memory than Minikube allocates by default to the Kubernetes clusters that it creates.  This commit adds a comment with an example command and suggested limits.
Also fix a minor typo in the Kafka instance definition and some formatting problems.
Fixes #92 
```release-note
NONE
```

Add note on creating a k8s cluster via minikube with more RAM / CPU

---

.circleci/config.yml
.gitignore
.goreleaser.yml
Makefile
RELEASE.md

Fixes #
Including circleci
Adding docs for release process
```release-note
NONE
```

Adding goreleaser

---

docs/examples/backups.md

The current documentation for this example is missing the steps necessary to define the custom plans in order to trigger a backup and a subsequent restore, so this commit adds those.
Fixes #167 
```release-note
NONE
```

Fix up the MySQL backup and restore example

---

docs/getting-started.md

Indented the bullet item for alternatively using kubectl to install CRDs. This should allow the `make run` bullet item to stay at the same level as the other steps and not be rendered to the same line after `kubectl apply -f config/crds`
Fixes #
```release-note
```

Fix up - indent install-crds alternative

---

config/samples/kafka-frameworkversion.yaml

/kind cleanup
Current kafka config sample can confuse the starters as it fails to get a healthy kafka broker pod. 
Fixes the kafka config sample as per kudobuilder/frameworks repo

fix the sample config for kafka

---

pkg/kudoctl/util/github/client_test.go

which was trying to fetch Flink framework versions from the incubating frameworks. Flink has been promoted to stable so we test with Redis instead.
>
> /kind bug
/kind cleanup
> /kind design
> /kind kep
Fixes #
```release-note
NONE
```

Fix `GetIncubatingFrameworkContentDir` unit test

---

pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/util/check/check.go
pkg/kudoctl/util/check/check_test.go

/kind cleanup
Right now the test was directly using os.Stat accessing the filesystem. That's not good idea in unit tests - then it cannot be run in an environment without .kubeconfig at the expected location.
One option I was investigating was using https://github.com/spf13/afero but then I decided to go with no extra dependencies and just refactored the code and test to not use the filesystem.
```release-note
NONE
```

Refactor unit test to not use filesystem

---

pkg/kudoctl/util/github/client_test.go

/kind bug
This test was failing. I think that it was asserting incorrect message. The credentials provided in that case are invalid so we cannot hit the rate limiter response.
Fixes #
```release-note
NONE
```

Fix failing test

---

Makefile

/kind bug
Use syntax recommended[0] by the Reproducible Builds project so that the
output of date in the desired format works across GNU and BSD userlands
[0] https://reproducible-builds.org/docs/source-date-epoch/
Fixes #265 
```release-note
NONE
```

Fix use of date command so it's compatible with BSD and GNU date

---

go.mod
pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/install_test.go

So instead of `kubectl kudo install kafka -p foo,bar` it would be: `kubectl kudo install kafka -p foo=bar`
Additionally, parameter validation is now done before the actual command execution to avoid potential failures down the road.
>
> /kind bug
> /kind design
> /kind kep
Fixes #225 
```release-note …
```

Use Helm-style parameters for `kudoctl kudo install` command

---

config/crds/kudo_v1alpha1_framework.yaml
pkg/apis/kudo/v1alpha1/framework_types.go

/kind api-change
Update the framework spec to include metadata defined in here: https://github.com/kudobuilder/kudo/blob/master/keps/0009-operator-toolkit.md#frameworkyaml
Part of Issue #269 
```release-note
None
```

Updated FrameworkSpec with metadata from KEP009

---

docs/cli.md
docs/deployment/00-prereqs.yaml
docs/deployment/10-crds.yaml
docs/deployment/20-deployment.yaml
docs/getting-started.md

Updates the documentation with instructions on how to easily create all the necessary RBAC prereqs, CRDs and stateful set.

Improve install experience

---

site/content/posts/announcing-kudo-0.2.0.md

Small fix for the actual command that is not `homebrew` but `brew`.
Fixes #
```release-note
NONE
```

Blogpost: Fixing homebrew tap cmd

---

test/Dockerfile
test/run_tests.sh

All CI runs now look like this:
```
Step 3/10 : COPY test/.git-credentials .git-credentials
COPY failed: stat /var/lib/docker/tmp/docker-builder611541570/test/.git-credentials: no such file or directory
Error when building test docker image, cannot run tests.
Tests finished successfully! ヽ(•‿•)ノ
```

Make the CI run again after git-credentials removal

---

RELEASE.md

**What type of PR is this?** 
Fixes #
```release-note
NONE
```

Update to Release Process

---

docs/cli.md
docs/deployment/00-prereqs.yaml

/kind bug
The Zookeeper sample fails with `Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:kudo-system:kudo-manager" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope`
This PR adds an authorization for `persistentvolumeclaims` to the `ClusterRole` and cleans up the docs.

Allow kudo-manager-role to modify persistentvolumeclaims to fix ZK

---

pkg/kudoctl/cmd/install/install.go

Fix error found by the linter. `make lint` passes after applying this patch.
```release-note
NONE
```

Fix error reported by linter

---

Makefile

`go lint` does not fail on errors by default without `-set_exit_status` present.

Fail on lint errors

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go

Summary:
- parameter parsing and validation now happens prior to the `install` command execution
- install `Options.Parameters` is now a map with keys and values (`map[string]string`) 
>
> /kind bug
> /kind design
> /kind kep
```release-note
NONE
```

Refactored install parameters

---

pkg/controller/framework/framework_controller.go
pkg/controller/frameworkversion/frameworkversion_controller.go
pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_suite_test.go

Summary:
previously we would only recognize Instance Spec parameter updates and fail to detect an update if a parameter would be added or removed. This is fixed now.
>
/kind bug
> /kind design
> /kind kep
Fixes #216 
```release-note
Previously we would only recognize Instance Spec parameter updates and …
```

Fix comparing parameter values on Instance Spec updates

---

CONTRIBUTING.md
docs/getting-started.md

Simplifies the getting started doc, trying to streamline the installation process minimizing the number of steps/dependencies required to get started with KUDO.
This PR also improves the documentation on how to build KUDO and start contributing to the project.
```release-note
NONE
```

Improve getting started and contributing docs

---

keps/0004-add-testing-infrastructure.md

/kind kep
This outlines our testing procedures, types, and policies.
```
NONE
```

Update KEP-0004 to describe testing procedures, types, and policies.

---

CONTRIBUTING.md
Makefile
pkg/test/case_test.go
pkg/test/harness_integration_test.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/kubernetes_test.go
test/Dockerfile

/kind cleanup
This gates integration tests behind the `integration` tag.
To run unit tests: `make test`
To run integration tests: `make integration-test`
Fixes #338
https://github.com/kudobuilder/kudo/pull/358 removes the rest of the autogenerated integration tests.
```release-note
NONE
```

Hide integration tests behind the integration build tag.

---

docs/community.md
docs/testing.md

Adds documentation for the KUDO test harness.
Fixes #340
Depends on https://github.com/kudobuilder/frameworks/pull/23
```release-note
* Initial release of KUDO test harness for testing Frameworks and KUDO.
```

Documentation for KUDO test harness.

---

go.mod
pkg/test/harness.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/kubernetes_test.go

/kind cleanup
Previously, the test harness would exit with failure if it was asked to install CRDs or manifests prior to running that already existed.
This PR uses the testutils CreateOrUpdate method to update the resources if they already exist.
```release-note
* Test harness will now update CRDs and Frameworks before being run, rather than exiting with failure.
```

[test harness] Use the test utils CreateOrUpdate method to update CRDs and manifests.

---

keps/0013-external-specs.md

/kind kep
Introduces KEP-0013 to accept a process non KUDO application formats
None
I did not address how KEP-0012 and KEP-0013 interact yet.  Once one of them get merged we can adjust the other.
```release-note
NONE
```

KEP-0013 External Application Formats

---

pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/util/repo/bundle.go
pkg/kudoctl/util/repo/package.go
pkg/kudoctl/util/repo/package_test.go
pkg/kudoctl/util/repo/repo_framework.go

/kind cleanup
/kind design
Refactors bundle (explanation follows)
1. This PR is built around the concept that there are 3 separate abstractions: bundle, packages and repository.  Prior to this PR they were all 3 conflated and bundle wasn't explicit and had more than 1 code path for the same abstraction (tarballs).  From my mental model, a bundle is a way to bundle package files (so they are closely related).   Bundles currently are files and tarballs, but one could also see zip files etc.   
2. This PR is built with the expectation that we should be able to get CRDs (packages) completely separate from how the bundle is found. A bundle could be local, could be a url to a tarball (not implemented), could be discovered in a …

Refactor of bundle

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go

/kind feature
This adds a `-skip-instance` flag that allows installing Operators and OperatorVersions without installing Instances. This is useful in a testing scenario - we install all of the Operators and OperatorVersions but don't want to install the Instances until later.
```release-note
kudoctl install now supports -skip-instance flag which skips installing an Instance when installing Operator and OperatorVersions.
```

Add -skip-instance flag to kudoctl install to skip installing instances.

---

pkg/controller/planexecution/planexecution_controller.go
pkg/controller/planexecution/planexecution_controller_test.go
pkg/test/utils/kubernetes.go

/kind bug
If the JSON patch returned no annotations or no spec, then the JSON that was created would be invalid.
```
2019/06/27 17:06:46 Going to apply patch
{"metadata": {"annotations": }, "spec": {"clusterIP":null,"ports":[{"name":"client","port":6379,"targetPort":6379},{"name":"gossip","port":16379,"targetPort":16379}],"sessionAffinity":null}}
to object
```
```release-note
NONE
```

Fix marshalling of patched objects.

---

pkg/test/test_data/immutable-client-ip/00-assert.yaml
pkg/test/test_data/immutable-client-ip/00-install-instance.yaml
pkg/test/test_data/immutable-client-ip/01-assert.yaml
pkg/test/test_data/immutable-client-ip/01-upgrade.yaml

/kind bug
Reproduce a bug in KUDO:
```
2019/06/28 01:49:40 Going to apply patch
{"metadata": {"annotations": {}}, "spec": {"clusterIP":null,"ports":[{"name":"gossip","port":80,"targetPort":0}],"sessionAffinity":null}}
to object
&Service{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:my-instance-svc,GenerateName:,Namespace:kudo-test-adapting-parakeet,SelfLink:/api/v1/namespaces/kudo-test-adapting-parakeet/services/my-instance-svc,UID:fded0ced-9946-11e9-9081-0242ac110002,ResourceVersion:98,Generation:0,CreationTimestamp:2019-06-28 01:49:39 +0000 …
```

Add test for immutable client IP bug

---

pkg/test/utils/kubernetes.go

/kind bug
The new CRDs that we generated have a `Kind` and `Plural` set, but not `Singular`. It seems like we should use Kind instead.
```release-note
NONE
```

Use Kind instead of Singular when looking up types in test harness.

---

pkg/kudoctl/cmd/install/install.go

There's a user expectation that if they've set the `KUBECONFIG` environment variable in their shell to a valid cluster configuration, this should be picked up and used.
Fixes #462 
```release-note
Allow use of KUBECONFIG shell environment variable as a way of specifying target cluster configuration.
```

Use KUBECONFIG envvar if set when creating a new client

---

pkg/test/harness.go

/kind cleanup
This prevents errors with KUDO trying to communicate with a control plane that has been shutdown.
```release-note
NONE
```

In test harness, stop KUDO first then stop the control plane.

---

pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/testing.go

/kind cleanup
Improve logs outputted by the kudo test harness:
* Always use verbose test logging.
* Log the envtest startup time.
* Log resources created/updated by CreateOrUpdate
```release-note
NONE
```

Small test harness logging improvements: enable verbose test logging, log created/updated resources, time to start test environment.

---

pkg/kudoctl/cmd/get/instances.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/plan/plan_status.go

As with #472, the `get` and `plan` KUDO commands should also honour the $KUBECONFIG environment variable, if it's set.
Fixes #462 
```release-note
Ensure the `get` and `plan` commands are also aware of the KUBECONFIG environment variable.
```

Look for KUBECONFIG environment variable for 'get' and 'plan'

---

CONTRIBUTING.md
pkg/apis/kudo/v1alpha1/test_types.go
pkg/kudoctl/cmd/test.go
pkg/test/case.go
pkg/test/harness.go
pkg/test/utils/testing.go

/kind feature
Support --skip-delete to skip deletion of resources created during tests.
This helps with debugging tests.
Also refactors the test harness CLI parsing to load configuration:
1. If `--config` is set, from the config specified.
2. If `--config` is not set and `kudo-test.yaml` exists, it loads it from `kudo-test.yaml`.
3. Arguments set on the command line override configuration from the configuration.
Previously you could only use CLI arguments or a configuration.
Fixes #377
```release-note
[test harness] Support --skip-delete to skip deletion of resources created during tests
```

Support --skip-delete to skip deletion of resources created during tests

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go

There are two changes in this PR:
- further simplified install, this time around OperatorVersion
- removed auto-approve option and thus removing interactive install
```release-note
--auto-approve option from `kudo install` was removed
```

Remove interactive install, more install refactoring

---

pkg/test/step.go
pkg/test/step_integration_test.go

/kind bug
When listing objects in the test harness, there was a bug where the for loop variable was appended to the list of objects to compare causing only the last object (alphabetically) in the namespace to be compared when checking if any objects match the assert.
This fixes it by indexing the list instead of taking the address of the loop variable.
Found by @gkleiman :)
```release-note
NONE
```

Fix matching objects when listing in test harness

---

docs/cli.md

small PR to fix documentation around kafka parameters
https://github.com/kudobuilder/operators/pull/40 is merged now
The PR goes along with changes in https://github.com/kudobuilder/operators/pull/40 so users don't face issues when following the docs and installing the `kafka` operator 
In KUDO examples we use ` --parameter KAFKA_ZOOKEEPER_URI` that would be now ` --parameter ZOOKEEPER_URI` etc
This PR should be merged once we have merged https://github.com/kudobuilder/operators/pull/40

kafka: update cli.md reference to kafka parameters

---

pkg/test/harness.go
pkg/test/step_integration_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

/kind bug
envtest can race when choosing the Kubernetes API port if multiple envtests are created simultaneously.
Instead of starting envtest within each test, we start envtest in a TestMain for the module. This means we do not
need to start as many envtests, as well as reducing our likelihood of racing over a Kubernetes API port.
We also retry creating envtest. If the API server does not come up, we will try twice to try to prevent any potential races.
Fixes #510
```release-note
NONE
```

Clean up integration tests that use controller-runtime envtest.

---

pkg/controller/planexecution/planexecution_controller.go
test/integration/create-operator-in-operator/00-dream.yaml
test/integration/create-operator-in-operator/01-assert.yaml
test/integration/create-operator-in-operator/01-install.yaml

/component operator
/kind bug
In https://github.com/kudobuilder/kudo/pull/447 we've added StrategicMergePatchs, however custom resources apparently don't work currently with SMPs. With this patch, CustomResources can behave properly without throwing:
```
PlanExecutionController: CreateOrUpdate Patch: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json
```
It works by being more verbose and catching the error of a failed StrategicMergePatch and applying an old MergePatch before throwing an error. When testing this …

Adding Ability to MergePatch CRDs properly

---

pkg/test/utils/kubernetes.go

/kind bug
If the user has no default route when running the tests, the Kubernetes API server will refuse to start as the --advertise-address argument is missing which makes Kubernetes look up the default address.
This appends a specific --advertise-address to the Kubernetes API server flags in integration tests.
Fixes #509 
Air plane mode :)
```release-note
NONE
```

Set the --advertise-address when starting Kubernetes API server in tests.

---

test/run_tests.sh

/kind bug
Increase the RAM limit for the test Docker container to 4 gigabytes. I saw a timeout with 2 gigabyte, so suspect that it did not have enough headroom.
```release-note
NONE
```

Increase Docker RAM allocation to 4 gigabytes.

---

keps/0008-operator-testing.md
pkg/apis/kudo/v1alpha1/test_types.go
pkg/test/case.go
pkg/test/harness.go
pkg/test/step.go

/kind bug
The KEP defined the default assertion timeout as 300 seconds, but we actually implemented it as 10 seconds. I think 300 seconds is much too high for the default, so I've adjusted it to 30 in both the implementation and KEP.
This also makes the timeout configurable at the test suite level so that it can be configured for an entire test suite instead of just a specific assert.
Fixes #532
```release-note
Test harness timeout is now configurable at the test suite level.
```

Fix default test timeout and make default test timeout configurable at the test suite level.

---

code-of-conduct.md

Wanted to inline the CoC since it links to Kubernetes, and then finally out to the CNCF. Users should just be able to see what we're about when they come to our repo.

Inline the Code of Conduct

---

test/integration/parse-param-operator-in-operator/00-dream.yaml
test/integration/parse-param-operator-in-operator/01-assert.yaml
test/integration/parse-param-operator-in-operator/01-install.yaml
test/manifests/test-operator.yaml

This test is for parsing parameters into operators that run operators. We test if the parsed parameters are applied successfully.
Fixes #
To run locally:
```
$ go run ./cmd/kubectl-kudo test --test=parse-param-operator-in-operator
```
Output will look like:
```
...
--- PASS: kudo (10.52s)
harness.go:85: started test environment (kube-apiserver and etcd) in 7.116559804s
--- PASS: kudo/harness (0.01s)
--- PASS: kudo/harness/parse-param-operator-in-operator (3.11s)
logger.go:37: 13:07:25 | parse-param-operator-in-operator | Creating namespace: kudo-test-big-tetra
logger.go:37: 13:07:25 | parse-param-operator-in-operator/0-dream | …
```

Adding Test for Parameter Parsing within Operators

---

pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

/kind bug
Implement a new RetryClient that wraps the Kubernetes Client with retries
This ensures that we properly retry on network failures in our integration tests to prevent an flaky tests.
Fixes #526
```release-note
NONE
```

Implement a new RetryClient that wraps the Kubernetes Client with retries

---

pkg/controller/instance/instance_controller.go

>
This PR cleans up and improves the readability of the instances controller. It improves comments, includes some refactoring code, and addresses an existing TODO.
I think that most of the code touched here should actually moved to the `Reconcile` method.
```release-note
NONE
```

Clean up instance controller

---

pkg/kudoctl/cmd/install.go

StringVarP doesn't include short command, but P does, so it was treating "v" as the default value. This fixes #544.

Change StringVar to StringVarP for version. Fixes #544

---

pkg/controller/planexecution/planexecution_controller.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/repo/repo_operator.go

/kind cleanup
Clean up of variable names `f` and `fv` which referred to Framework and FrameworkVersion to `o` and `ov` for Operator and OperatorVersion.
Fixes #
```release-note
NONE
```

Fixed missed variable name changes from move to operator

---

pkg/test/harness.go
pkg/test/harness_test.go

/kind bug
Fix configuring kudo test assert timeouts via the kudo-test.yaml configuration file.
```release-note
Bug fixed related to configuring Kudo test timeout via TestSuite or CLI.
```

Fix configuring kudo test assert timeouts via configuration file

---

.circleci/config.yml
docs/deployment/20-deployment.yaml

/kind cleanup
This PR is against `releases/0.3` branch and is in preparation for the `v0.3.2` release.   It makes our CRDs useable for the release they are tagged in.
Fixes #
```release-note
NONE
```

Switch CRD version reference to the next release

---

pkg/controller/planexecution/planexecution_controller.go

/kind bug
This PR fixes the issues of planexecution not passing the correct default params 
and showing in logs: 
```
PlanExecutionController: parameter cpus was required but not provided by instance zk
```
```
PlanExecutionController: parameter LOG_CLEANER_IO_BUFFER_LOAD_FACTOR was required but not provided by instance kafka
```
```release-note
```

fix planexecution controller to check parameter default also

---

.goreleaser.yml

/kind bug
We discovered in the process of releasing `v0.3.2` that the latest goreleaser uses the project folder as the default name of the build id.  Since we have 2 builds, they both had the same build id.   We needed to provide proper discreet build ids.
Fixes #
```release-note
NONE
```

Add Build IDs to gorelease Release Builds

---

Makefile

/kind bug
Fixes #577 
```release-note
NONE
```

Makefile build info should be identical to goreleaser build info

---

Makefile

/kind bug
Fixes #
```release-note
NONE
```

Back-Port: Makefile build info should be identical to goreleaser build info (#579)

---

pkg/controller/planexecution/planexecution_controller.go
test/integration/patch/00-assert.yaml
test/integration/patch/01-assert.yaml

/kind bug
controller was adding version labels with every patch of an object. This is fine for all objects except statefulsets.
```
"volumeClaimTemplates": [
{
"metadata": {
...
"labels": {
....
"version": "0.1.0"
}
```
that was causing the same error as helm was dealing with here https://github.com/helm/charts/issues/7803
Fixes #557 
```release-note
Fixes upgrades for operators using statefulsets - it was not possible to upgrade those to another version of template.
```

Fix operator upgrades

---

keps/0008-operator-testing.md
pkg/test/step_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

/kind feature
This makes it so that if a namespace is set in a resource in a test step or assert that namespace is respected instead of being overwritten with the test case's namespace. This allows tests to be written that span multiple namespaces or test resources that exist in a specific namespace (e.g., check the status of `core-dns` in `kube-system`).
N/A
```release-note
Tests can now create and assert on resources in any namespace.
```

Respect namespaces if they are set in test harness.

---

pkg/apis/kudo/v1alpha1/test_types.go
pkg/kudoctl/cmd/test.go
pkg/test/harness.go

/kind feature
If a KIND cluster is used for the tests, we collect its logs at the end of the test run into the configurable `--artifacts-dir` (or `.`, if not specified).
```release-note
The test harness now collects logs from kind at the end of test runs.
```

Support collecting cluster logs with kind.

---

pkg/kudoctl/cmd/test.go

/kind cleanup
Fix the default kind context to match kind's default.
kind defaults to "kind" and not "default" for the cluster context:
```
➜  kudo git:(fix-default-kind) ✗ kind create cluster --help
Creates a local Kubernetes cluster using Docker container 'nodes'
Usage:
kind create cluster [flags]
Flags:
--config string   path to a kind config file
-h, --help            help for cluster
--image string    node docker image to use for booting the cluster
--name string     cluster context name (default "kind")
--retain          retain nodes for debugging when cluster creation fails
--wait duration   Wait for control plane node to be ready (default 0s)
Global Flags:
--loglevel string   logrus log level [panic, fatal, error, …
```

Fix the default kind context to match kind's default.

---

pkg/controller/planexecution/planexecution_controller.go

/kind bug
Instead of issuing a Get after Create or Patch in the PlanExecution controller, we use the objects that were updated by the Create and Patch method to prevent read-after-write cache consistency issues.
We also save ourselves a Get because of this :)
**Fixes**:
Fixes #602 
```release-note
Fixed cache consistency issue in PlanExecution controller.
```

Do not Get after Create/Patch in plan execution controller

---

pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

/kind feature
This adds a basic `Watch` method to the RetryClient which allows a user to Watch all events on a specific resource for use in integration tests.
This is needed to allow @fabianbaier to write a test for the step delete behavior in #599. Eventually, this will be used to implement #600 when we replace the test harness's polling with watching events.
This is probably not the most efficient way to implement the watches... I figured we would start here and optimize the internals of the method as necessary, but if anyone knows how to make it better we could do that here too.
```release-note
NONE
```

Add a Watch method to the RetryClient

---

.circleci/config.yml

/kind bug
This removes the merge before running tests in Circle CI. I believe this check provides no value as it runs at *commit time* and not at *merge time*, so there are no guarantees that this even tests the correct merge target and creates difficulty with PR branches. To enforce merge safety, we should use GitHub branch settings.
Fixes #568
```release-note
NONE
```

Remove merge check from circle CI configuration.

---

pkg/test/test_data/create-or-update/00-assert.yaml
pkg/test/test_data/create-or-update/00-crd.yaml
pkg/test/test_data/create-or-update/01-assert.yaml
pkg/test/test_data/create-or-update/01-create-deployment.yaml
pkg/test/test_data/create-or-update/01-create-known-crd.yaml
pkg/test/test_data/create-or-update/01-create-service.yaml
pkg/test/test_data/create-or-update/01-create-unknown-crd.yaml
pkg/test/test_data/create-or-update/02-assert.yaml
pkg/test/test_data/create-or-update/02-update-deployment.yaml
pkg/test/test_data/create-or-update/02-update-known-crd.yaml
pkg/test/test_data/create-or-update/02-update-service.yaml
pkg/test/test_data/create-or-update/02-update-unknown-crd.yaml
pkg/test/utils/kubernetes.go
test/integration/immutable-client-ip/01-upgrade.yaml
test/integration/instance-controller-param-change-custom-trigger/01-update-instance.yaml
test/integration/instance-controller-param-change-fallback-to-deploy/01-update-instance.yaml
test/integration/instance-controller-param-change-no-trigger/01-update-instance.yaml
test/integration/patch/01-plan-update.yaml
test/integration/step-delete/01-upgrade.yaml

/kind bug
This fixes the test harness to use a merge patch instead of `Update`. In our previous use of `Update`, we were replacing entire objects when updating them (e.g., if `status` is not defined in YAML it would get wiped out on update). Instead of using `Update`, we use the merge patching method.
We do *not* use strategic merge patch as it does not work with CRDs and my tests indicate the proper behavior that we want is achieved using only merge patch.
Additionally, as a side effect of this change, only minimal updates need to be defined in test steps.
If validated well, this can guide the implementation of `CreateOrUpdate` in KUDO (or be the implementation of `CreateOrUpdate`).
**Does this PR introduce a …

Use merge patch instead of Update method in test harness.

---

docs/testing.md
pkg/test/step.go
pkg/test/test_data/delete-in-step/00-assert.yaml
pkg/test/test_data/delete-in-step/00-create.yaml
pkg/test/test_data/delete-in-step/01-assert.yaml
pkg/test/test_data/delete-in-step/01-create.yaml

Fix test harness deletion to be able to delete all resources in a namespace.
Fixes #636
```release-note
Test harness steps are now able to delete all resources of a given type in a namespace.
```

Fix test harness deletion to be able to delete all resources in a namespace.

---

pkg/controller/instance/instance_controller.go
test/integration/create-operator-in-operator/00-dream.yaml
test/integration/create-operator-in-operator/01-install.yaml
test/integration/parse-param-operator-in-operator/00-dream.yaml
test/integration/parse-param-operator-in-operator/01-install.yaml
test/integration/step-delete/00-install-instance.yaml

/kind bug
When OV is created AFTER instance, this is how we look for existing instances https://github.com/kudobuilder/kudo/blob/master/pkg/controller/instance/instance_controller.go#L87 so the labels have to be in place
Fixes #626 
```release-note
NONE
```

Fix race between OV and I creation in tests

---

pkg/controller/planexecution/planexecution_controller.go

/kind bug
If an Instance does not exist, the PlanExecution controller returns an error when its PlanExecution is reconciled. Because the PlanExecution controller returns an error if the Instance does not exist and controller-runtime will automatically requeue an object for reconciliation if an error is returned, we essentially enter an infinite loop reconciling deleted Instances.
This modifies the method to only log that the Instance does not exist and not return an error so that it will not be requeued.
This cuts test run time from ~80 seconds to ~20 and fixes the flakiness with the create-operator-in-operator test.
```release-note …
```

Do not requeue PlanExecution reconciliation if Instance does not exist.

---

Makefile
go.mod
go.sum
pkg/apis/kudo/v1alpha1/test_types.go
pkg/apis/kudo/v1alpha1/zz_generated.deepcopy.go
pkg/test/case.go
pkg/test/case_test.go
pkg/test/harness.go
pkg/test/step.go
pkg/test/test_data/cli-test/00-assert.yaml
pkg/test/test_data/cli-test/00-create-pod.yaml
pkg/test/test_data/cli-test/test_data/pod.yaml
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go
test/integration/cli-install/00-assert.yaml
test/integration/cli-install/00-install.yaml
test/integration/cli-install/01-assert.yaml
test/integration/cli-install/01-upgrade.yaml
test/integration/cli-install/cli-install-operator/operator.yaml
test/integration/cli-install/cli-install-operator/params.yaml
test/integration/cli-install/cli-install-operator/templates/deployment.yaml

/kind feature
This adds a `kubectl` setting to the KUDO test harness TestSuite and TestStep configurations to support running kubectl commands as a part of tests.
Fixes #368 (support CLI commands)
Fixes #369 (support install kudo frameworks)
Fixes #520 (panic when executing test harness)
```release-note
Test harness now supports running kubectl commands as a part of tests.
```

Implement CLI and E2E testing using the KUDO test harness.

---

RELEASE.md
hack/generate_krew.sh

This adds a script that can generate a krew plugin manifest from the output of goreleaser. I don't know if there's a way to run this with goreleaser, but if there is we should do that.
Fixes #276 
```release-note
NONE
```

Add script for generating a krew plugin manifest.

---

docs/testing.md
docs/testing/asserts.md
docs/testing/reference.md
docs/testing/steps.md
docs/testing/test-environments.md
docs/testing/tips.md
site/config.yml
site/layouts/docs/baseof.html

This overhauls the test harness documentation to be better.
These docs are for 0.4.0 release. So, some of the things in here are aspirational:
* We don't yet have a krew plugin.
* CLI testing is not yet implemented.
```release-note
NONE
```

Overhaul test harness documentation.

---

hack/generate_krew.sh

/kind cleanup
This fixes the Krew plugin path for Windows EXEs.
```release-note
NONE
```

Fix EXE path when generating Krew plugin.

---

go.mod
go.sum
pkg/controller/instance/instance_controller.go
pkg/controller/planexecution/planexecution_controller.go

/kind cleanup
While working #634 it was challenging to resolve those 3 bugs.  It is generally agreed that instance controller needs to be refactored.  It is not coded according to the recommendations of https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg.  The predicates have side effects.   All reconciliation activities should move to the reconciler.  @alenkacz and I paired this morning and took on everything at once.  As I continued that work, it seemed logical to break it appear into several PRs.   This is the work for `Create` operation of instance controller.   It includes:
1. …

Instance Controller:  Refactored Create Operation

---

site/content/posts/announcing-kudo-0.4.0.md

Add blog post for 0.4. release to the website

Add 0.4.0 blog post

---

docs/contributing.md

First attempt at documenting a sane PR review process, mostly cribbed from the Kubernetes one.
This commit adds a contributing section to our documentation which gives would-be developers and reviewers some guidance and setting of expectations.
Fixes #419 
```release-note
NONE
```

Add contributing section to documentation

---

pkg/kudoctl/cmd/get.go
pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/update.go
pkg/kudoctl/cmd/upgrade.go
pkg/kudoctl/cmd/version.go

/kind cleanup
Commands previously were inconsistent with usage info... some used the default (like `test` and `get`) however several overrode the default help.   All the overrides resulted in the help text not be displayed at all.   For instance `go run cmd/kubectl-kudo/main.go update --help`
resulted in:
```
Update installed KUDO operator with new parameters.
Usage:
kubectl-kudo update <instance-name> [flags]
Flags:
-h, --help                    help for update
--kubeconfig string       Path to your Kubernetes configuration file (default "/Users/kensipe/.kube/config")
--namespace string        The namespace where the instance you want to upgrade is installed in. (default "default")
-p, --parameter …
```

Consistent help messages for all commands

---

pkg/kudoctl/cmd/update.go
pkg/kudoctl/cmd/update_test.go
test/integration/update-command/01-update.yaml
test/integration/update-command/02-add-new-param.yaml
test/integration/update-command/03-update-param-value.yaml

/kind cleanup
this unifies the feel of kudo update, upgrade and install.
Until this PR, the situation was looking as follow:
```
kudo install <package-location> --instance <instance-name> -p a=b
kudo upgrade <package-location> --instance <instance-name> -p a=b
kudo update <instance-name> -p a=b
```
Fixes #
```release-note
NONE
```

Unify feel of install, upgrade and update

---

docs/getting-started.md

Seems like the rendered files don't have a `.md` ending.

Fix broken link to developing-operators

---

pkg/test/utils/kubernetes.go

/kind test
This fixes flake in `TestCreateOrUpdate` https://circleci.com/gh/kudobuilder/kudo/4560?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
As we're using controller-runtime client that has cache built in it can happen, that `Get` returns no instance but we can no longer create that entity because it exists. I think we should always retry such cases as at one point the cache gets populated and we will hit the update branch and everything will end as success :)
Fixes #639 
```release-note
NONE
```

Fix flake in CreateOrUpdate

---

docs/getting-started.md

Based on simplistic testing, [here](https://docs.google.com/spreadsheets/d/1QXr5726SMlrGxFkLup7UfJrJaM1oaRRw1aK2uTcjvoY/edit#gid=0), minimum minikube requirements to deploy zk and kafka is 4cpu and 10gig of memory.

update min minikube spec to allow zk/kafka

---

site/content/posts/announcing-kudo-0.2.0.md
site/content/posts/announcing-kudo-0.3.0.md
site/content/posts/announcing-kudo-0.4.0.md
site/content/posts/announcing-kudo-0.5.0.md
site/data/events/kubernetesfinland.yaml

The date for the Kubernetes and CNCF Meetup in Finland has changed, so we need to update our events page to reflect that.
This commit also fixes a broken link to the community page from the release announcements.
```release-note
NONE
```

Update date for K8s Finland Meetup, fix community link in announcements

---

config/crds/kudo_v1alpha1_instance.yaml
config/crds/kudo_v1alpha1_planexecution.yaml
config/crds/kudo_v1alpha1_teststep.yaml
config/crds/kudo_v1alpha1_testsuite.yaml
hack/update_manifests.sh
pkg/apis/kudo/v1alpha1/planexecution_types.go
pkg/apis/kudo/v1alpha1/zz_generated.deepcopy.go
pkg/controller/instance/instance_controller.go
pkg/controller/planexecution/planexecution_controller.go

/kind feature
As part of #422 to be able to cleanly reconcile instance we need to be able to say from what state of instance the previous plan was ran (to be able to diff params etc.) as kubernetes does not guarantee for us to hold history of instance objects.
The design of this is inspired by deployment x replicaset x pod relation in core k8s. There also RS references whole podspec and when deployment is updated, they try to figure out if that RS has the same podspec or what changed.
This is just first step, as we introduce the instance spec on that CRD and make sure it's filled when planexecution is created. to use that for processing, that will come in the next PR. …

Instance spec as part of plan execution CRD

---

docs/developing-operators.md

* Make path absolute, otherwise it points to `/docs/developing-operators/docs/testing
* Remove `.md` ending
/component operator

Fix testing link

---

docs/cli.md
pkg/kudoctl/cmd/update.go

Fixes the the example in the docs for the `kubectl kudo update` command as this is currently incorrect (you need to prefix the instance name with `--instance`).
I've also tried to fix up some of the wording and naming used inline in the subcommand itself as well as in the documentation.
```release-note
NONE
```

Fix some wording around the update subcommand

---

keps/0015-repository-management.md
keps/draft-repo.md

/kind kep
KEP for automating the repository
Fixes #
```release-note
NONE
```

KEP:  Draft For Repository (targeted for KEP-15)

---

pkg/bundle/operator.go
pkg/kudoctl/util/repo/index.go
pkg/kudoctl/util/repo/index_test.go
pkg/kudoctl/util/repo/repo.go
pkg/kudoctl/util/repo/testdata/flink-index.yaml.golden

/kind bug
Fixes #748 
```release-note
NONE
```

switching maintainer back to 0.5.0 release and adding marshaling tests

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init_test.go
pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/install_test.go
pkg/kudoctl/cmd/root.go
pkg/kudoctl/cmd/upgrade.go
pkg/kudoctl/cmd/upgrade_test.go
pkg/kudoctl/env/environoment.go
pkg/kudoctl/util/repo/repo.go
pkg/kudoctl/util/repo/repo_operator.go
pkg/kudoctl/util/repo/repo_test.go

/kind feature
Adds use of kudo repositories and repo name for install and upgrade
`go run cmd/kubectl-kudo/main.go install --repo-name=community test` will fail on not find `test` but it did find the repo
`go run cmd/kubectl-kudo/main.go install --repo-name=foo test` will fail because it can not find the repo.
The default repo is used if `kudo init --client-only` is not executed.
Fixes #
```release-note
--repo can now be used with `install` and `upgrade`
```

Uses Repo Name in kudo install and upgrade

---

keps/0008-operator-testing.md

/kind kep
Currently the test harness only supports running kubectl commands and plugins, but this is limiting:
* It prevents testing Helm charts (you cannot use Helm).
* It prevents using kind subcommands (e.g., `kind load docker-image`).
This would have us support the `Commands` setting to allow this flexibility.
The downside is that now tests can call arbitrary commands. Alternatively, we could retain the kubectl restriction and require helm/kind/etc to be installed as kubectl plugins in order to be used in tests.
```release-note
NONE
```

Proposal: Support calling out to arbitrary commands in the test harness.

---

.circleci/config.yml
Makefile
test/run_tests.sh

The '[go-junit-report](https://github.com/jstemmer/go-junit-report)' project is used to convert `go test` output to a JUnit XML report. CircleCI is instructed to store these test results.
Fixes #703
```release-note
NONE
```

Collect test metadata in integration tests

---

.gitignore
Makefile
go.sum
keps/0008-operator-testing.md
pkg/apis/kudo/v1alpha1/test_types.go
pkg/test/harness.go
pkg/test/step.go
pkg/test/test_data/cli-test/01-assert.yaml
pkg/test/test_data/cli-test/01-patch.yaml
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

/kind test
This implements the test commands feature to support running commands that are not kubectl plugins, see #754 for more details.
To use, set:
```
apiVersion: kudo.dev/v1alpha1
kind: TestSuite
commands:
- command: kubectl kudo init
```
Or:
```
apiVersion: kudo.dev/v1alpha1
kind: TestStep
commands:
- command: kubectl label mypod label=true
namespaced: true
```
```release-note
The test harness now supports running non-kubectl-based commands as a part of tests.
```

Implement test commands feature

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init_test.go

/kind cleanup
The trailing period is too easy to pick up when selecting text in your terminal to copy.
Also it looks weird.
```release-note
NONE
```

Nit: Remove the trailing period after printing $KUDO_HOME

---

hack/check_formatting.sh
hack/generate_krew.sh
hack/update_codegen.sh
hack/update_manifests.sh
test/run_tests.sh

/kind cleanup
These shell scripts have been linted with [shellcheck](https://www.shellcheck.net/) and made consistent by
* Using `bash` for all scripts
* Indenting with 4 spaces
* Having 'then' in the same line as 'if'
* Using the same options for all scripts
* Using `$(...)` notation instead of backticks
* Removing `grep` when `awk` alone can do the job
This also fixes an issue with `docker pull` retries not working in `test/run_tests.sh`.
```release-note
NONE
```

Lint shell scripts and ensure consistency

---

.circleci/config.yml
Dockerfile
build/test-images.sh
test/Dockerfile

Bump Go 1.13 
Fixes #
```release-note
NONE
```

Bumping go version to 1.13 for builds and tests

---

README.md

Changed to working link: https://kudo.dev/docs/
**Does this PR introduce a user-facing change?**: No

fix broken link to getting started

---

pkg/kudoctl/cmd/repo.go

/kind bug
Fixes #772 
```release-note
NONE
```

Fixing repo command short message

---

pkg/controller/instance/instance_controller.go
pkg/controller/planexecution/planexecution_controller.go

The flakes I have seen were all in operator-in-operator test. The reason for them was that in this PR  https://github.com/kudobuilder/kudo/commit/47e7da741a71e35ef21d6ad708afb55e520b70cf I have moved code to create PE relation to instance controller, but that means that we need to make sure that reconciliation is triggered not only after PE is created but also after PE is linked to instance. That was not happening for the instance in instance example because I was triggering reconcile only for the outer instance.
Fixes #766

Fix flake in operator-in-operator test

---

pkg/test/case.go

* Print out events after finishing test run

Backport (0.6): Proposal to print out events after finishing test run (#797)

---

.github/workflows/release-on-master.yml

I put this on the Github Marketplace so others could use it, which doesn't allow you to have a monorepo of actions.
Located here: https://github.com/marketplace/actions/current-time

Updates current-time to published version

---

pkg/kudoctl/cmd/get.go
pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/package.go
pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/repo.go
pkg/kudoctl/cmd/repo_add.go
pkg/kudoctl/cmd/repo_context.go
pkg/kudoctl/cmd/repo_index.go
pkg/kudoctl/cmd/repo_list.go
pkg/kudoctl/cmd/repo_remove.go
pkg/kudoctl/cmd/root.go
pkg/kudoctl/cmd/test.go
pkg/kudoctl/cmd/update.go
pkg/kudoctl/cmd/upgrade.go
pkg/kudoctl/cmd/version.go

/kind cleanup
There were inconsistencies in the CLI and the following is what this PR cleans up:
* `-o` was used for overwrite and for output.  It is now only for output.  `-w` is overwrite.
* We needed more examples and better formatting of the examples.  All examples are 2 spaces in, thus the output looks like:
```
Examples:
kubectl kudo repo remove local
kubectl kudo repo rm local
```
with 2 space indention to the example section
* Long descs were either elaborated or removed (if they were a dup of the short)
* misspelling of "remmove" -> "remove"
* All long descs were pulled up to a const
* Descs in Examples were moved to Long desc... examples are examples
CLI now has a consistent look across commands.
**Which …

CLI cleanup

---

pkg/test/harness.go

Just a very minor/cosmetic thing. I think it would be nice to see in logs what was value of the timeout for the suite you're running.

Log a timeout that is going to be used for the suite

---

pkg/kudoctl/clog/log.go
pkg/kudoctl/clog/log_test.go
pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init/manager.go
pkg/kudoctl/cmd/init_test.go
pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/root.go
pkg/kudoctl/cmd/upgrade.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/repo/repo_operator.go

/kind feature
Adds -v as a global flag of verbosity
Adds easy logging for developer clog.V(5).Printf - provides stdout if verbosity is level 5.  The default level is 0
Adds convenient prints of messages that should always go to stdout `clog.Printf`
Adds convenient prints for Errorf, which is at level 2.
```
go run cmd/kubectl-kudo/main.go install zookeeper  
instance.kudo.dev/v1alpha1/zookeeper-rkt85t created
```
```
go run cmd/kubectl-kudo/main.go install zookeeper  -v 3
acquiring kudo client
getting package crds
no local operator discovered, looking for http
no http discovered, looking for repository
operator name: zookeeper
operator version: 0.1.0
parameters in use: map[]
operator.kudo.dev/zookeeper unchanged
instance …
```

Clog Client Controlled Verbosity (-V)

---

test/integration/first-operator-test/00-assert.yaml
test/integration/first-operator-test/00-install.yaml
test/integration/first-operator-test/01-assert.yaml
test/integration/first-operator-test/01-scale.yaml

/kind test
This ensures that changes in KUDO are reflected in this example.
Fixes #827 
```release-note
NONE
```

Add an integration test for the 'first-operator' example

---

pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/install/install_test.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go
pkg/version/version.go
pkg/version/version_test.go
test/integration/upgrade-command/first-operator/operator.yaml
test/integration/upgrade-command/second-operator/operator.yaml

/kind feature
Adding check of operator requested kubernete version against the server.  
`kubernetesVersion` is now a required field for operators
Fixes #
```release-note
kubernetesVersion is a required operator field
```

Kubernetes Version Server Check For Kudo Install

---

pkg/test/harness.go
pkg/test/harness_test.go
pkg/test/utils/docker.go

This adds a call to `NegotiateAPIVersion()` when initializing our Docker API client so that it will work with any Docker version:
```
harness.go:172: error creating volume for node Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39
```

Negotiate Docker API version before attempting to create node volumes in tests.

---

pkg/kudoctl/cmd/package_test.go
pkg/kudoctl/packages/finder/package_finder.go
pkg/kudoctl/packages/package.go
pkg/kudoctl/packages/package_manager.go
pkg/kudoctl/util/repo/repo_operator.go

* `io.Reader` was used for 2 things, buffers and files.  Buffers were fine, but were obfuscated as to when a buffer was used or a file.  Additionally leaving as a Reader left the opportunity for future confusion.  It is now a byte.Buffer.  In the one case where a file was passed the file is read to buffer.
This fixes this comment: // FIXME: Implement 'io.Closer' and make sure that it is called. 'tarPackage' will leak a file descriptor otherwise.
* Additionally the hastily merged refactor of bundle left confusing variables in places which are resolved.
* tests were modified for changes
* clog used in places for verbose logging
* refactored method names to match changes

Proper io.Closing around Packages

---

pkg/kudoctl/clog/log.go
pkg/kudoctl/cmd/init/crds.go
pkg/kudoctl/cmd/init/manager.go
pkg/kudoctl/cmd/init/prereqs.go
pkg/kudoctl/cmd/init_integration_test.go
pkg/kudoctl/kube/config.go

error handling for kudo init now continues if the error is the resource already exists
Fixes #742 
Replaces #790 
```release-note
NONE
```

Init Error Handling Enhancement

---

pkg/kudoctl/packages/package.go
pkg/kudoctl/util/repo/index_test.go
pkg/kudoctl/util/repo/repo.go
pkg/kudoctl/util/repo/testdata/flink-index.yaml.golden

removing fields from structs for which we do not want to expose thru yaml
This should be consistent with the discussion and agreements reached when discussing #847 
Fixes #

Removal of Struct Elements Based on Agreements for YAML Changes

---

pkg/test/harness.go

The logging now happens many times because it's inside the for cycle. This fixes that.

Log test timeout only once, not per file

---

pkg/test/step.go
pkg/test/step_test.go
test/integration/first-operator-test/01-errors.yaml

YAML files ending with 'errors' list objects that aren't expected in a
cluster's state. Tests will fail if any of these objects is found as part of a
test step.
Needed for integration tests of https://github.com/kudobuilder/kudo/pull/856

Add 'errors' file handling to test harness

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init/manager.go

StatefulSets were being created using the v1beta2 APIs, which have been removed from Kubernetes 1.16, causing this command to silently fail. The err value is being set correctly - this PR doesn't address that it's being swallowed. To make it even better, --dry-run and -o yaml work because "apps/v1" is being set correctly for the pretty printer.

Fix kudo init on Kubernetes 1.16

---

pkg/controller/instance/plan_execution_engine.go

This was a nasty, subtle one.
Health checks were getting a zero value status because we were passing in the locally made object into the health checker, rather than the fully resolved one from the client.

Fix health checks by passing in the resolved remote resource

---

pkg/kudoctl/cmd/plan.go
pkg/kudoctl/env/environoment.go

This commit adds the `-n` shorthand option for the `--namespace` global flag, mirroring the behaviour of `kubectl`.
It also removes the redundant flag definition elsewhere since `--namespace` is global, and tidies the help default for another.
Fixes #874

Add shorthand `-n` for `--namespace`

---

RELEASE.md

Adds a task to create w release announcement blog post to kudobuilder/www
This links to an internal docs page that is added via kudobuilder/www#51

Add a task for blog post to RELEASE.md

---

pkg/controller/instance/apply_conventions.go
pkg/controller/instance/plan_execution_engine.go
pkg/controller/instance/plan_execution_engine_test.go
pkg/util/kudo/labels.go
test/integration/instance-controller-param-change-custom-trigger/00-setup.yaml
test/integration/instance-controller-upgrade/00-setup.yaml

This is remaining cleanup from the PE/I controller refactoring. There were some leftover fields that should have been deleted in that PR but were left behind. Now nothing should reference PlanExecution hopefully.

Remove remaining mentions/usages of PlanExecution in code

---

pkg/controller/instance/instance_controller.go
pkg/controller/operator/operator_controller.go
pkg/controller/operatorversion/operatorversion_controller.go

Last week we were wondering if one of the bug was introduced by one of these annotations actually going away so I went and investigate how these actually work right now in our codebase and surprise, surprise - they don't do anything. 
We removed `make manifests` in this PR https://github.com/kudobuilder/kudo/commit/f513b1a3972669817d9a638e2ae50fe738f945bd#diff-d78b6f30225cdc811adfe8d4e7c9fd34 and that was the last usage of `controller-gen` which is the tool used to process these. We don't really generate rbac or crds or webhook anymore anyway so droping these markers as well is the way to go.
Documentation if someone is interested https://book.kubebuilder.io/reference/markers.html

Delete kubebuilder markers

---

keps/0004-add-testing-infrastructure.md
keps/0014-pull-request-process.md

* Removed the references of Prow in CICD.
* Added the reason for rejecting Prow.
Fixes #767

Removed the references of Prow in CICD.

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init/manager.go
pkg/kudoctl/cmd/init_test.go

This was the main motivation for this PR https://github.com/kudobuilder/kudo/compare/av/init-small-improvements?expand=1#diff-c74faa6263971005d609e60d78ff0f8eL171 I think the message is no longer true and we should be skipping all already exists errors now, correct? The rest is just small wording improvements.

Small improvements to the kudo init command and docs

---

pkg/controller/instance/apply_conventions.go
pkg/controller/instance/instance_controller.go
pkg/controller/instance/plan_execution_engine.go
pkg/controller/instance/plan_execution_engine_test.go

Yesterday when working on tasker with @zen-dog we identified these small things that were left behind in the refactoring, especially embedding the one metadata in the other seems like a natural choice.

Little bit of polishing in the execution engine

---

pkg/kudoctl/cmd/root.go

Fixes #896 
This will prevent `kudoctl` from printing usage when it subcommands RunE functions fails

silence usage when kudoctl run commands fail

---

cmd/manager/main.go

This enables operator developers to use CRDs. This scheme isn't explicitly added by core APIs. @kensipe when we go to CRDv1 we'll need to add that to the scheme as well. We won't want to remove this one because we don't necessarily mind if someone wants to manage CRD/v1beta1 CRDs via KUDO.
This is blocking someone, so I'd like to cherry pick this to 0.7.3 as well and ship it tomorrow.

Add API Extensions v1beta1 to scheme

---

pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/plan/plan_status.go

I think this is what broke it #882
Fixes #924

Fix namespace handling for plan command

---

pkg/controller/instance/plan_execution_engine.go
pkg/controller/instance/plan_execution_engine_test.go

Fixes two issues:
- we were using shallow copy and it was wrong because struct contains slices
- we modified the original state in `prepareKubernetesResources` which worked exactly because the shallow copy was a wrong choice but it's not what we want to do

Fix deep copy and don't modify original state

---

pkg/test/step_integration_test.go

I spent quite some time investigating this flake and I must admit my defeat :) All my hunches proved not to be true. Anyway it looks like all the tests run correctly in their own namespace, I was not able to reproduce locally.
The only thing that looked suspicious was that petname generator library uses the same seed (but the default source should be safe for concurrent use so that looks right).
So this PR is just an attempt. It renames the other pod that was also named 'aa' in case those somehow end up running in the same namespace, even though I did not prove that to be true.
We'll see if this helped at all :)
Relates to #829

Attempt to fix 'TestCheckResourceIntegration' flaky test

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden

This is cherry-pick of (#923) with small tweak in golden files

Include CRDs in the -o yaml --dry-run

---

pkg/controller/instance/plan_execution_engine.go
test/integration/install-existing-crds-in-operator/00-assert.yaml
test/integration/install-existing-crds-in-operator/00-install-operator.yaml
test/integration/install-existing-crds-in-operator/crd-operator/operator.yaml
test/integration/install-existing-crds-in-operator/crd-operator/params.yaml
test/integration/install-existing-crds-in-operator/crd-operator/templates/crd.yaml

Do not use strategicmergepatch for CRDs

---

pkg/kudoctl/cmd/install/install.go

Before this change, we just printed out instance was created but we did not do that for the other CRDs which can be confusing.
```
./bin/kubectl-kudo install ./config/samples/first-operator
instance.kudo.dev/v1alpha1/first-operator-zljnmj created
```
After
```
./bin/kubectl-kudo install ./config/samples/first-operator
operator.kudo.dev/v1alpha1/first-operator created
operatorversion.kudo.dev/v1alpha1/first-operator-0.1.0 created
instance.kudo.dev/v1alpha1/first-operator-ztrwtp created
```

More consistent logging for install

---

pkg/kudoctl/cmd/repo_index.go
pkg/kudoctl/util/repo/repo.go

Repo Configurations with Stringer for dereferencing in logs
Fixes #928

Repo Configurations with Stringer for dereferencing in logs

---

.circleci/config.yml
Makefile
hack/run-integration-tests.sh
test/Dockerfile
test/run_tests.sh

Make it possible to opt out of junit

---

pkg/test/step_integration_test.go

This is another attempt to fix this flaky test. I believe this one has better chance of succeeding :)
As I found out, we're using retry client in tests (whether it's right or not, I started a discussion in kudo channel). Anyway since that is the case right now, create can be retried and run two times so hitting already exists can happen.
Fixes #829

Handle already exists in flaky test

---

cmd/manager/main.go
go.mod
go.sum
pkg/test/harness.go
pkg/test/utils/dynamicrestmapper.go
pkg/util/template/template.go
pkg/util/template/template_test.go
test/integration/operator-with-custom-crd/00-assert.yaml
test/integration/operator-with-custom-crd/00-install-crd.yaml
test/integration/operator-with-custom-crd/01-assert.yaml
test/integration/operator-with-custom-crd/01-install.yaml
test/integration/operator-with-custom-crd/operator/operator.yaml
test/integration/operator-with-custom-crd/operator/params.yaml
test/integration/operator-with-custom-crd/operator/templates/sm.yaml

When scheme did not contain that type, we previously failed. Since we should be able to handle all types that people might have installed in their cluster, we should fallback to parsing a type as unstructured when not available.
This PR has 3 parts:
- update to `ParseKubernetesObjects` to process unknown types as Unstructured
- use of dynamic restmapper in execution that ensures that we discover new types that were added during the lifetime of the controller
- integration test
NOTE: Right now we are using dynamic mapper from test harness. That is probably not as robust as the one introduced in the controller-runtime 0.3.0. I will port this code to the controller-runtime mapper when we bump the version of controller-runtime (that should happen prior …

Handle unknown types as unstructured

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init/manager.go

Right now when you run init and you're initializing the server side as well as local environment, the only thing the command prints out is that local was initialized. This PR adds more logging to make it obvious that server side is being initialized as well.
This is output of init before this change
```
➜  kudo git:(av/maintainers-array) ✗ ./bin/kubectl-kudo init
$KUDO_HOME has been configured at /Users/alenavarkockova/.kudo
```
After
```
➜  kudo git:(av/init-logging) ✗ ./bin/kubectl-kudo init
$KUDO_HOME has been configured at /Users/alenavarkockova/.kudo
✅ installing crds
✅ preparing service accounts and other requirements for controller to run
✅ installing kudo controller
```

Better logging for init

---

pkg/apis/kudo/v1alpha1/instance_types.go
pkg/apis/kudo/v1alpha1/instance_types_test.go
pkg/controller/instance/instance_controller_test.go

🤦‍♀ pointers in for-cycle. Again.
Look at like 167, where I take pointer of p. Then in the second iteration I was comparing p and lastExecuted, which was &p which was the same thing.
Fixes #947

Fix flaky GetLastExecutedPlanStatus

---

pkg/kudoctl/cmd/plan/plan_history.go

This fixes a bug in reporting of history for non-existent instances and also polishes the output.
```
kudo git:(av/plan-history-fix) ✗ ./bin/kubectl-kudo plan history --instance nonexistent
Error: client Error: instance default/nonexistent does not exist
```
```
kudo git:(av/plan-history-fix) ✗ ./bin/kubectl-kudo plan history --instance first
.
└── deploy (last finished run at 2019-10-17T14:11:14 (COMPLETE))
```
Fixes #915 #940

Fix plan history bug

---

cmd/manager/main.go
go.mod
go.sum
pkg/test/harness.go
pkg/test/utils/dynamicrestmapper.go
pkg/util/template/template.go
pkg/util/template/template_test.go
test/integration/operator-with-custom-crd/00-assert.yaml
test/integration/operator-with-custom-crd/00-install-crd.yaml
test/integration/operator-with-custom-crd/01-assert.yaml
test/integration/operator-with-custom-crd/01-install.yaml
test/integration/operator-with-custom-crd/operator/operator.yaml
test/integration/operator-with-custom-crd/operator/templates/sm.yaml

Backport of https://github.com/kudobuilder/kudo/commit/5459b7d37c13c6678af07a1623d6d4b35fe056b6

Handle unknown types as unstructured (#954)

---

pkg/controller/instance/instance_controller_test.go
pkg/kudoctl/cmd/plan/plan_history.go

Wrapping errors in log messages results in structs showing up in the printed
text. Instead of '%w', '%v' is used instead which gives the expected results.
Fixes #940

Remove error-wrapping from log messages

---

pkg/kudoctl/util/repo/repo.go

Right now this is output of install
```
kudo git:(master) ✗ ./bin/kubectl-kudo install ./config/samples/first-operator
repo configs: { name:community, url:https://kudo-repository.storage.googleapis.com }
operator.kudo.dev/v1alpha1/first-operator created
operatorversion.kudo.dev/v1alpha1/first-operator-0.1.0 created
instance.kudo.dev/v1alpha1/first-operator-527jgn created
```
This PR removes the first line. I find it very cryptic and not aligned with the rest of messages we try to print out even in terms of format.

Remove printf with repo during install

---

hack/run-e2e-tests.sh

by running them against the `dev` branch of the operators repo which is held compatible with KUDOs bleeding-edge development including breaking API changes etc.

Fix e2e-tests

---

pkg/kudoctl/cmd/init/prereqs.go
pkg/kudoctl/cmd/init_integration_test.go
pkg/kudoctl/cmd/init_test.go
pkg/kudoctl/cmd/testdata/deploy-kudo-ns-default.yaml.golden

Makes `init` command handle only `kudo-system` namespace. Other
namespaces are expected to be created beforehand.
Fixes #972

init: handle only "kudo-system" namespace

---

hack/update_codegen.sh

Running `make generate` on freshly cloned repo results in error. Running `make generate` second time works fine.
Steps to reproduce:
1. Clone the repo
2. Run `make generate`
```bash
❯ make generate
./hack/update_codegen.sh
Cloning into 'hack/code-gen/c2090bec4d9b'...
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 7425 (delta 86), reused 137 (delta 56), pack-reused 7240
Receiving objects: 100% (7425/7425), 4.40 MiB | 2.11 MiB/s, done.
Resolving deltas: 100% (3615/3615), done.
HEAD is now at c2090be Merge remote-tracking branch 'origin/master' into release-1.13
go: creating new go.mod: module k8s.io/code-generator
go: copying requirements from …
```

Fix `make generate` on clean repository

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/packages/package.go
pkg/kudoctl/packages/package_test.go
pkg/kudoctl/packages/testdata/zk-crd-golden1/instance.golden
pkg/kudoctl/packages/testdata/zk-crd-golden2/instance.golden

Remove the random string suffixed onto the end of instance names, instead using a suffix of 
`-instance`.  Users can use the `--instance` option to provide a unique name if they so wish.
Fixes #948

Make Instance name deterministic

---

pkg/kudoctl/cmd/get/get.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/uninstall.go
pkg/kudoctl/cmd/update.go
pkg/kudoctl/cmd/upgrade.go
pkg/kudoctl/env/environment.go
pkg/kudoctl/env/environment_test.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go

Add an option (`--request-timeout`) to allow the user to specify the KUDO client's request
timeout.  The hardcoded default of 3 seconds causes problems for users whose connectivity to a target service involves relatively significant amounts of latency. 
Mirror the behaviour of `kubectl` by copying the option itself and setting this to by default to 0 (no timeout).
Fixes #955

User-configurable request timeouts

---

.circleci/config.yml
Makefile

Additionally, renamed `code-formatting` CircleCI job to `lint`.

`make lint` doesn't install `golinter` if found one locally

---

pkg/engine/renderer/enhancer.go
test/e2e/cli-install-uninstall/00-assert.yaml
test/e2e/cli-install-uninstall/02-errors.yaml
test/integration/cli-install/01-assert.yaml
test/integration/create-operator-in-operator/01-assert.yaml
test/integration/first-operator-test/00-assert.yaml
test/integration/first-operator-test/01-assert.yaml
test/integration/immutable-client-ip/00-assert.yaml
test/integration/immutable-client-ip/01-assert.yaml
test/integration/operator-test/00-assert.yaml
test/integration/operator-test/01-assert.yaml
test/integration/parse-param-operator-in-operator/01-assert.yaml
test/integration/update-parameters/00-assert.yaml
test/integration/update-parameters/01-assert.yaml
test/integration/update-parameters/02-assert.yaml

Right now we prepend name of the instance to all resources, we decided to step away from that because it's not suitable for certain kinds of resources like namespaces.
Fixes #945

Do not autogenerate names of resources

---

Makefile

I just noticed this when reviewing #996
We removed all kustomize handling from config folders, init is the only way to go now.

Remove kustomize from Makefile - we don't use it anymore

---

go.mod
go.sum
pkg/engine/renderer/engine.go

The canonical import path for `sprig` is [github.com/Masterminds/sprig](https://github.com/Masterminds/sprig). Using different cases can lead to issues when trying to import KUDO packages in other projects.
This PR also updates `sprig` to v2.22.0.

Fix incorrect case of 'sprig' import

---

.goreleaser.yml

Straightforward, this is in advance of today's pre-release.

Prevent goreleaser from uploading pre-release homebrew builds

---

.circleci/config.yml

Everytime we tag a release, this job fails because it's not really set up fully and it does not copy our full release practices. I think we should re-introduce it once we're ready for that, remove it for now.
Fixes #

Remove circleci release job

---

pkg/engine/workflow/engine.go

Right now, when transient error happens, we don't see the error in logs at all. Since workflow engine is kind of swallowing the errors (which is expected) it should log them too.

Log out retry-able errors

---

Makefile

Since deploy is installing everything into a cluster, deploy-clean should remove everything. Right now it was removing just crds.

Deploy clean should remove everything, not just CRD

---

build/Dockerfile
pkg/test/test_data/create-or-update/00-assert.yaml

Kubernetes api server had a race back in 1.13 https://github.com/kubernetes/kubernetes/issues/51353 and we're still seeing this in our tests because we're using api-server from 1.13.1 in tests. We run tests in docker and we use tools provided by kubebuilder release. We depend on 1.0.8 which is kube 1.13.1. By going to 2.X we;re at least moving to 1.15
I looked into ditching kubebuilder altogether because we're really just using api server and etcd but it would be a bit more work :) we could do it as follow-up if people find it meaningful.
If tests locally start to fail for you after this PR, it's because you need to update api server locally as well if you're not running tests inside docker.'
Oh and this is just first step of the fix - the real will …

Update API server for tests

---

go.mod
go.sum
pkg/kudoctl/env/environment.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go

CRDs aren't tied to a namespace. By checking for them directly through the 'apiextensions' client is a cleaner approach than checking if listing CRDs objects succeed. This also make the `namespace` parameter of `kudo.NewClient` redundant.

Improve the check for KUDO CRDs when creating a client

---

pkg/test/test_data/crd-in-step/00-assert.yaml

Otherwise creation of the custom resource races with CRD establishment,
and fails in case it wins.

Wait for CRD to be established.

---

CONTRIBUTING.md

Adds documentation workaround for issue with code-generator that causes `generate-groups.sh` to fail due to a missing `GOPATH`.
See https://github.com/kubernetes/code-generator/issues/87.

Add build instructions workaround for an issue with code-generator.

---

config/crds/kudo_v1beta1_instance.yaml
pkg/apis/kudo/v1beta1/instance_types.go
pkg/controller/instance/instance_controller.go
pkg/kudoctl/cmd/init/crds.go
pkg/kudoctl/cmd/testdata/deploy-kudo-ns-default.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden

Currently, our Instance CRD contains status but we don't have status subresource enabled. That means that we're vulnerable to this behavior described in API conventions:
```
The PUT and POST verbs on objects MUST ignore the "status" values, to avoid accidentally overwriting the status in read-modify-write scenarios. A /status subresource MUST be provided to enable system components to update statuses of resources they manage.
Otherwise, PUT expects the whole object to be specified. Therefore, if a field is omitted it is assumed that the client wants to clear that field's value. The PUT verb does not accept partial updates. 
```
Fixes #1043

Enable status subresource for instance CRD

---

pkg/kudoctl/cmd/uninstall.go

This is the new output. I think that is much more user friendly.
```
./bin/kubectl-kudo uninstall mysql-instance
Error: The command expects no arguments and --instance flag must be provided.
Usage:
kubectl-kudo uninstall [flags]
Examples:
kubectl kudo uninstall --instance flink
Flags:
-h, --help              help for uninstall
--instance string   The instance name.
Global Flags:
--home string           location of your KUDO config. (default "/Users/alenavarkockova/.kudo")
--kubeconfig string     Path to your Kubernetes configuration file. (default "/Users/alenavarkockova/.kube/config")
-n, --namespace string      Target namespace for the object. (default "default")
--request-timeout int   Request timeout value, in seconds.  Defaults to 0 (unlimited) …
```

Better output when incorrect args in uninstall

---

pkg/kudoctl/packages/writer/writer_tar.go
pkg/kudoctl/packages/writer/writer_test.go

For reproducible builder, certain file metadata has to be changed for archives. This is described in https://reproducible-builds.org/docs/archives/. File ordering is guaranteed by afero, file modification times and uid/gid are changed before adding them to the tarball.
Fixes #1066

Make package builds reproducible

---

go.mod
go.sum
pkg/engine/renderer/enhancer.go
pkg/test/step_test.go

This should not be a breaking change as we were already depending on CR few commits behind this, just that now it was officially released. We should probably do tests agains pre-1.16 kubernetes on this anyway just to be sure.
There were 2 "breaking" changes in CR that affected us:
- fake client started adding resource version https://github.com/kubernetes-sigs/controller-runtime/pull/620/files which affected the `step_test` because one of the resources had this extra field
- https://github.com/kubernetes-sigs/controller-runtime/pull/675/files - that was actually bug on our side that CR just made obvious. Read #1073 for full context
Fixes #

Bump controller-runtime to 0.4.0

---

pkg/controller/instance/instance_controller.go
pkg/kudoctl/util/repo/index.go
pkg/kudoctl/util/repo/repo_operator.go
pkg/kudoctl/util/repo/resolver_repo.go

which holds all the methods related to resolving a package in a repo. This is a minor followup cleanup PR to #1047.

Introduced a `resolver_repo.go`

---

hack/update_codegen.sh

Also, do no attempt to run it if `go.mod` already exists.
See subject.
Fixes #1051

Properly handle `go mod init` failures.

---

CONTRIBUTING.md

Reverts kudobuilder/kudo#1068 now that the v2 book is back up.

Revert "Fix broken link."

---

pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/plan/plan_status.go
pkg/kudoctl/cmd/plan/plan_status_test.go
pkg/kudoctl/cmd/root.go

This is follow-up of #1050 
It stops using dynamicclient in this command and introduces first unit tests for the output.
This PR does not aim to add full test coverage for that command but from that point on, it will be easier to add tests when needed.

Refactoring of plan_status and first unit tests

---

pkg/kudoctl/util/kudo/kudo.go

We can NOT wrap the timeout error associated with a bad kubeconfig.  It is private error which can be interrogated to determine that it was a `Timeout` however that ability doesn't work if wrapped.  
When the cluster is down or not started DNS requests from go will fail on Line 142 of https://golang.org/src/net/dial.go with an error which is private (internal).  It can not be wrapped because it can't be unwrapped.
Fixes #
This part 1 of a 2 part solution towards fixing bug  #1056

better error handling when working with kube and kudo.

---

build/test-images.sh

We no longer support Golang < 1.13 nor use these images.

Stop creating old test images.

---

go.mod
go.sum
pkg/engine/renderer/enhancer.go
pkg/engine/workflow/engine_test.go
pkg/kudoctl/cmd/get/get.go
pkg/kudoctl/cmd/init/wait.go
pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/package_create.go
pkg/kudoctl/cmd/package_params_list.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/repo_context.go
pkg/kudoctl/cmd/repo_remove.go
pkg/kudoctl/cmd/test.go
pkg/kudoctl/cmd/update.go
pkg/kudoctl/cmd/upgrade.go
pkg/kudoctl/packages/package.go
pkg/kudoctl/packages/reader/parser.go
pkg/kudoctl/packages/reader/read_dir.go
pkg/kudoctl/packages/reader/reader_tar.go
pkg/kudoctl/packages/reader/reader_test.go
pkg/kudoctl/util/repo/index.go
pkg/kudoctl/util/repo/repo_operator.go
pkg/kudoctl/util/repo/resolver_repo.go
pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go

Removes a dependency
Because... reasons... 
Fixes #

removal of github.com/pkg/errors and commitment to go 1.13 errors

---

CONTRIBUTING.md

This is a first outline of our code culture that mostly came out of retrospectives we had in the last 2 months.
This is for sure not a definitive list, let's add more points in next PRs though. Let's make this PR just about the points mentioned and if everyone is OK with them and with the wording.
Please let's keep this PR open longer so that everyone have chance to see it.

Introduce our code culture in contributing.md

---

pkg/kudoctl/cmd/package_test.go
pkg/kudoctl/packages/reader/read_dir.go
pkg/kudoctl/packages/reader/reader_tar.go
pkg/kudoctl/packages/resolver/resolver_local.go
pkg/kudoctl/packages/resolver/resolver_url.go
pkg/kudoctl/util/repo/resolver_repo.go

Log package origins when installing
Log local paths with absolute path
Improved error messages
Fixes #1101 
The original error case: User has a directory "kafka" in the cwd:
```
aneumanns-MBP:kudo aneumann$ go run ./cmd/kubectl-kudo/main.go install kafka --instance=kafka
kafka is a local file package
Error: failed to resolve package CRDs for operator: kafka: while parsing package files: operator package missing operator.yaml in /Users/aneumann/git/kudo/kafka
exit status 255
```
New output without "kafka" directory in cwd:
```
aneumanns-MBP:kudo aneumann$ go run ./cmd/kubectl-kudo/main.go install kafka --instance=kafka
kafka is a repository package from { name:community, url:https://kudo-repository.storage.googleapis.com } …
```

Log package origins

---

hack/update_codegen.sh

go.mod has been a part of code-generator since April 2019 so we don't
need the other code path
I only noticed [Jan's comment about this](https://github.com/kudobuilder/kudo/pull/1052#pullrequestreview-319025672) today.

Stop calling go mod init in code-generator.

---

CONTRIBUTING.md

Extend contributing.md with more examples

---

pkg/kudoctl/cmd/init_test.go

In my webhook PR, I refactored init tests, but in the meantime, SA test landed. This just moves the SA test into the table tests thus fixing the code duplication.

SA init test moved into table tests

---

pkg/kudoctl/packages/reader/parser.go

which was broken for template files due to a Linux path separator.
Fixes: #893

Fix package parser on windows

---

cmd/manager/main.go

**What would you like to be added**:
To add a cmd arg to kudo-manager to make the kudo-manager reconcile resync period configurable. 
```
bin/manager [-sync-period]
```   
**Why is this needed**:
The default operator generated by kubebuilder has the default SyncPeriod set to 10 hours which sometimes prevents kudo-manager to update instance resource as the cached instance object resourceversion might older than the latest in k8s cluster. 
**Issues we found**:
```
kudo-controller-manager-0 manager 2019/12/02 06:31:21 PlanExecution: default/zk-kudo all phases of the plan deploy are ready
kudo-controller-manager-0 manager 2019/12/02 06:31:21 InstanceController: Error when updating instance state. Operation cannot be fulfilled on instances.kudo.dev "zk-kudo": the object has been modified; …
```

add reconcile resync period to cmd arg to avoid stall resource caching

---

pkg/apis/kudo/v1beta1/instance_validator.go
pkg/apis/kudo/v1beta1/instance_validator_test.go

For now, we disallowed all updates except status updates. This narrows it down and just disallows updates to the spec that means:
- no change in params
- no change in OV
This potentially narrows down issues with the webhook as controller etc. can update annotation or finalizers, which I think is fine even when plan is running.
Addition to #883

Disallow only spec updates for now

---

pkg/engine/task/task_pipe.go
pkg/engine/task/task_pipe_test.go

These methods are not storing anything, just creating resources as strings.

Rename store methods to create methods in pipes

---

pkg/kudoctl/cmd/init.go

- do not use the cryptic 'mans'
- do not reuse the `prereq` variable

Rename some variables.

---

pkg/kudoctl/cmd/init/prereqs.go
pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden

Fixed yaml output for kudo init with custom SA
Fixed integration test that expected the custom SA and RB manifests in yaml output #1165
Fixes #1165

Fixed yaml output for kudo init with custom SA

---

CONTRIBUTING.md

The DCO is much more simple, and we don't need a bot to verify, just need to see that commits have been signed.

Change KUDO to using DCO instead of CLA

---

pkg/kudoctl/cmd/init_test.go
pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
pkg/kudoctl/kudoinit/manager/manager.go

Do not mount cert volume when webhook disabled

---

pkg/test/step.go

* Previously, the test timeout was ignored when waiting for resources deleted by a TestStep to disappear. This changes it so that the test assert timeout is respected and used.

Wait for the entire assert timeout for resources to be deleted.

---

STYLEGUIDE.md

* move a k8s.io import to correct section in example
* mention `make import`
* add links to code conventions

Fix example, add links, mention `make import`

---

config/crds/kudo_v1beta1_instance.yaml
config/crds/kudo_v1beta1_operatorversion.yaml
pkg/apis/kudo/v1beta1/instance_types.go
pkg/apis/kudo/v1beta1/operatorversion_types.go
pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
pkg/kudoctl/kudoinit/crd/crds.go

This in preparation of moving to generating CRDs from the structs, in
order to minimize the diff.
Baby step towards https://github.com/kudobuilder/kudo/issues/862

Unify description spelling in cmd and pkg/apis.

---

pkg/apis/kudo/v1beta1/operatorversion_types.go
pkg/apis/kudo/v1beta1/test_types.go

This is a re-post of #1181  which was merged into the wrong branch.
Example messages:
```
pkg/apis/kudo/v1beta1/test_types.go:93:2: encountered struct field "Labels" without JSON tag in type "ObjectReference"
Error: not all generators ran successfully
```
This does not seem to have any effect otherwise.
This is another baby step towards #862

Use empty json tags to please controller-gen.

---

pkg/kudoctl/cmd/plan/plan_status.go
pkg/kudoctl/cmd/plan/plan_status_test.go

Phase strategy can be defined independently of that for a plan, so this commit includes this in the output so that the Operator behaviour is less confusing to the user.
The output of that command now looks like this:
```
Plan(s) for "zookeeper-instance" in namespace "default":
.
└── zookeeper-instance (Operator-Version: "zookeeper-0.2.0" Active-Plan: "deploy")
├── Plan deploy (serial strategy) [COMPLETE]
│   ├── Phase zookeeper (parallel strategy) [COMPLETE]
│   │   └── Step deploy [COMPLETE]
│   └── Phase validation (serial strategy) [COMPLETE]
│       ├── Step validation [COMPLETE]
│       └── Step cleanup [COMPLETE]
└── Plan validation (serial strategy) [NOT ACTIVE]
└── Phase connection (serial strategy) [NOT ACTIVE]
├── Step connection [NOT …
```

Include phase strategy in plan status output

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init_integration_test.go
pkg/kudoctl/kudoinit/crd/crds.go
pkg/kudoctl/kudoinit/manager/manager.go
pkg/kudoctl/kudoinit/prereq/namespace.go
pkg/kudoctl/kudoinit/prereq/prereqs.go
pkg/kudoctl/kudoinit/prereq/serviceaccount.go
pkg/kudoctl/kudoinit/prereq/webhook.go
pkg/kudoctl/kudoinit/setup/setup.go
pkg/kudoctl/kudoinit/setup/wait.go
pkg/kudoctl/packages/package.go
pkg/kudoctl/util/kudo/kudo.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

Some files didn't sort their imports as described in our styleguide. This has been fixed.

Arrange import sections following our styleguide

---

hack/generate_krew.sh

This fixes the build in https://github.com/kubernetes-sigs/krew-index/pull/389

Windows CLI is not currently built for KUDO so do not include in Krew manifest.

---

config/crds/kudo_v1beta1_operatorversion.yaml
pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
pkg/kudoctl/kudoinit/crd/crds.go

The goal is to make CRDs and the api structs match.
I'm not sure whether this is the way to go - are these the fields that the
current ongoing "versioning" discussion is all about?
In that case perhaps we should instead remove these fields (and code which uses
them, if any) from the structs?
This is a baby-step towards #862.

Add appVersion and version to CRD to match the structs.

---

config/crds/kudo_v1beta1_instance.yaml
config/crds/kudo_v1beta1_operator.yaml
config/crds/kudo_v1beta1_operatorversion.yaml
pkg/kudoctl/cmd/get/get_test.go
pkg/kudoctl/cmd/plan/plan_status_test.go
pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
pkg/kudoctl/cmd/uninstall_test.go
pkg/kudoctl/cmd/update_test.go
pkg/kudoctl/kudoinit/crd/crds.go
pkg/kudoctl/kudoinit/manager/manager.go
pkg/kudoctl/kudoinit/prereq/namespace.go
pkg/kudoctl/packages/package.go
pkg/kudoctl/packages/testdata/zk-crd-golden1/instance.golden
pkg/kudoctl/packages/testdata/zk-crd-golden1/operator.golden
pkg/kudoctl/packages/testdata/zk-crd-golden1/operatorversion.golden
pkg/kudoctl/packages/testdata/zk-crd-golden2/instance.golden
pkg/kudoctl/packages/testdata/zk-crd-golden2/operator.golden
pkg/kudoctl/packages/testdata/zk-crd-golden2/operatorversion.golden
pkg/kudoctl/util/kudo/install_test.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go
pkg/kudoctl/util/kudo/upgrade_test.go

- remove the "app: kudo-manager" from CRDs, since it is not really used
by anything, and will be hard to convince controller-gen to generate
it when we switch to it
- remove the controller-tools.k8s.io label, (which is not even used by
controller-tools upstream any more) from EVERYWHERE
This is another baby step towards #862

Remove some unused labels.

---

pkg/apis/kudo/v1beta1/instance_types.go
pkg/apis/kudo/v1beta1/test_types.go

These make the output closer to what is defined in kudoinit.
This is a baby-step towards #862.

Add annotations for controller-gen.

---

pkg/apis/kudo/v1beta1/operatorversion_types.go
pkg/apis/kudo/v1beta1/zz_generated.deepcopy.go

It seems to me like using the full-blown type with spec, status and all had been a mistake.
This field seems unused in the code, so maybe that is why this was missed.
This is a baby step towards #862.

Use the correct type for UpgradableFrom.

---

pkg/apis/kudo/v1beta1/operatorversion_types.go

This makes the description match (missed in on of the earlier PRs) and adds a
missing field.
This is a baby step towards #862.

Bring the structs in line with the CRDs.

---

STYLEGUIDE.md

The `staticcheck` and `vet` linters are included in `golanci-lint` and run as part of `make lint`. This has been added in https://github.com/kudobuilder/kudo/pull/994, but didn't update the styleguide accordingly.

Remove obsolete linting steps from the styleguide

---

config/crds/kudo_v1beta1_operatorversion.yaml
pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
pkg/kudoctl/kudoinit/crd/crds.go

Result of discussion in #1198.
It was never used (verified by eyeballing `git log -p` all the way
down), we don't seem to know what it's for, and it has no counterpart in
the structs.
This is a baby step towards #862.

Remove the unused crdVersion from CRD.

---

Makefile

Currently we have a single file in each of these, so the effect is the same.
However it will save us some frustration if we ever add more, and this way
reflects the intent better.
This was discovered the [hard way](https://github.com/markbates/pkger/issues/57) trying to get `pkger`
working for #862.

When building binaries, compile the whole package.

---

hack/run-e2e-tests.sh
hack/run-integration-tests.sh
pkg/test/utils/kubernetes.go

-   Show what commands are being run.
This makes it easier to get the most focused command for the thing that is
failing.
-   Show the actual binary which is run.

Improve test transparency.

---

pkg/apis/kudo/v1beta1/test_types.go
pkg/test/harness.go
pkg/test/harness_test.go
pkg/test/kind.go
pkg/test/kind_integration_test.go
pkg/test/utils/docker.go

In preparation for https://github.com/kudobuilder/kudo/issues/1177, this PR refactors the `test` packages to have a `kind` struct that is a thin abstraction layer for running KinD clusters.
It adds the 'kindContainers' option to the test harness. This option allows to add (local) Docker images to a KinD cluster, e.g. when testing local artifacts.
Solves #684

Refactor KinD usage in test harness and allow to add (local) containers

---

pkg/test/utils/kubernetes.go

This removes some excessive printing that I believe was introduced by accident, e.g.,:
```
=== RUN   TestWaitForCRDs
&APIResourceList{GroupVersion:apiextensions.k8s.io/v1beta1,APIResources:[]APIResource{APIResource{Name:customresourcedefinitions,Namespaced:false,Kind:CustomResourceDefinition,Verbs:[create delete deletecollection get list patch update watch],ShortNames:[crd crds],SingularName:,Categories:[],Group:,Version:,StorageVersionHash:jfWCUB31mvA=,},APIResource{Name:customresourcedefinitions/status,Namespaced:false,Kind:CustomResourceDefinition,Verbs:[get patch update],ShortNames:[],SingularName:,Categories:[],Group:,Version:,StorageVersionHash:,},},}2019/12/27 00:08:39 CustomResourceDefinition:/instances.kudo.dev created …
```

Remove unnecessary accidental debug logging from test harness

---

pkg/test/utils/kubernetes.go

Currently when generating KubeConfig Kudo is not reading the files for CA when generating a KubeConfig within the test context that it is running in. This comes into play if you have a component that is using the generated Kubeconfig to make calls to the Kubernetes API within your test. According to the [docs](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) ca bundles are handled like so when accessing the k8s api using a service account: 
> If available, a certificate bundle is placed into the filesystem tree of each container at /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, and should be used to verify the serving certificate of the apiserver.
This patch simply reads that file and loads it into the kubeconfig …

Adds a fix to include CA data in generated kubeconfig

---

.circleci/config.yml

It is necessary for code gen to be apart of the build process to ensure that code is clean... 
Personally I would prefer we do NOT check in generated code.

Adding code gen to CI build

---

pkg/kudoctl/cmd/verify/verify.go
pkg/kudoctl/packages/verifier/task/verify_references.go
pkg/kudoctl/packages/verifier/task/verify_references_test.go

Realized with lots of work on operators and skeleton generators that we could use verification on plan tasks and defined tasks since they are loosely coupled by name.
This PR provides a new "PlanVerifier" which provides warnings for tasks that are defined but are not used in a plan and an error for tasks in a plan that are not defined.
Fixes #

Verifier for tasks and plans

---

Makefile
pkg/kudoctl/kudoinit/crd/bindata.go

Follow up to https://github.com/kudobuilder/kudo/pull/1211 
It is not OK to not lock in the version of the build tool chain.
Also the file gen is out of date :(

need to lock in version of generators

---

.circleci/config.yml
hack/verify-generate.sh
pkg/kudoctl/kudoinit/crd/bindata.go

The problem I with #1231 is that we're not just checking generate exit code but we're also **generating files in CI** and we're then running build and tests on those generated files instead on those checked in. Because of that, if someone forgets to check in their generated file as part of commit, this won't be catched in CI because CI will build on code that was produced by running the introduced `make generate`.
One solution would be to remove generated files from git and always force people to generate. I see two problems with that:
- generate is pretty slow, just when I was debugging this PR, I spent so much time just waiting for it to finish, I cannot see that doing before every build
-  it's recommended and even required if your code is used …

Check that generated files are up to date

---

go.mod
pkg/controller/instance/instance_controller.go
pkg/engine/renderer/enhancer.go

Kustomize was quite heavy dependency for ONLY adding annotations, labels and namespaces. This PR just assigns those directly on runtime.Objects (Unstructured). This also fixes cryptic errors we were getting from kustomize.
Fixes #1180 
Fixes #1179
Fixes #1163

Get rid of dependency on kustomize in controller

---

pkg/engine/renderer/enhancer.go
pkg/engine/task/render.go
pkg/engine/task/task_apply.go
pkg/engine/task/task_apply_test.go
pkg/engine/task/task_delete.go
pkg/engine/task/task_pipe.go
pkg/engine/workflow/engine_test.go

These are now meaningless after we've switched away from kustomize
recently.
I think these were simply missed in #1234

Remove the stale references to `kustomize`.

---

CONTRIBUTING.md
go.mod
go.sum

We can now use the version with fixed GOBIN/GOPATH support and remove the note
in instructions.
Apart from some changed dependencies, there do not seem to be any changes.
See https://github.com/kudobuilder/kudo/issues/1051#issuecomment-554023073 and https://github.com/kudobuilder/kudo/pull/1069 for old context.

Bump code generator and remove stale workaround note.

---

go.mod
go.sum
pkg/apis/kudo/v1beta1/instance_types.go
pkg/controller/instance/instance_controller.go
pkg/kudoctl/packages/verifier/template/parser_test.go
pkg/test/kind_integration_test.go

which implements map, filter, etc. methods for slices and maps. The first commit replaces existing implementations of the `contains` method through the codebase.

Adding funk library to the project

---

go.mod
go.sum
pkg/kudoctl/kudohome/home_test.go
pkg/kudoctl/util/repo/index_test.go
pkg/version/version_test.go

This removes the "properties" dependency and uses "testify" instead. The main reason was that the assertions provided by "properties" didn't correctly show the line in which an assertion failed. "testify" does. E.g. "properties" showed `assert.go:24: got 1.7.2 want  flink app version` while "testify" shows
```
index_test.go:63: 
Error Trace:	index_test.go:63
Error:      	Not equal: 
expected: ""
actual  : "1.7.2"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-
+1.7.2
Test:       	TestParseIndexFile
Messages:   	flink app version
```
Also this improves code consistency by removing a package when we have other packages already providing that functionality.

Replace 'properties/assert' with 'testify/assert'

---

pkg/apis/kudo/v1beta1/operatorversion_types.go

My guess is that they were meant for https://github.com/go-validator/validator
but this library does not seem to be used (any more?).
We do not seem to be using these tags for anything, they are not enforced, and
the current codebase violates them.
I did try to make the CRD validation markers match the tags in the process of
fixing #862, but there is plenty of test code which violates those rules, so it
would be a bigger task at this point.
Since these tags contradict the +optional markers on directly preceding lines,
it is best we reduce confusion by removing them.

Remove confusing no-op `validate:` tags.

---

Dockerfile
Makefile
hack/run-e2e-tests.sh
kudo-e2e-test.yaml.tmpl
test/Dockerfile

A Docker image of the KUDO manager is built and deployed in the E2E test cluster.
This is done by adding the build KUDO image to the KinD cluster and changing the 'kubctl kudo init' output to ensure that this image will be used when deploying KUDO.
Fixes #1177

Run a KUDO deployment for E2E testing

---

pkg/kudoctl/cmd/package_list_plans.go

Make lint happy again.
This was result of a race between merging https://github.com/kudobuilder/kudo/pull/1223 and https://github.com/kudobuilder/kudo/pull/1245

Check the type assertion on funk.Keys return value.

---

.goreleaser.yml

This PR forces the base image for the controller to be updated before releasing
The current release process does not force the Release Manager to update the base image (`ubuntu:18.04`) before releasing our controller.  This has caused releases to go out with vulnerabilities that were fixed in new versions of `ubuntu:18.04`, but not be part of the image that was used for release:
(All vulnerabilities found via https://github.com/anchore/anchore-engine )
Current vuln list for `ubuntu:18.04`
```bash
$ anchore-cli image vuln ubuntu:18.04 all
Vulnerability ID        Package                                  Severity          Fix         CVE Refs        Vulnerability URL
CVE-2009-5155           libc-bin-2.27-3ubuntu1                   Low …
```

Forces pulling down base image before building new image via goreleaser

---

hack/update_codegen.sh

This is a workaround for the code generators requiring $GOPATH to put output in the correct location.
Details in the issue.
Fixes #1252

Fake being in GOPATH when generating code.

---

pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/upgrade.go

better message.  the previous message was confusing around CRDs which isn't true.  we are trying to resolve an operator package
Fixes: #1272

Remove "CRDs" from Error Messages when resolving Operator Packages

---

pkg/kudoctl/cmd/repo_index_test.go
pkg/kudoctl/util/repo/resolver_repo.go
pkg/kudoctl/util/repo/resolver_repo_test.go

Refactored name to findfirst which is what it is doing and added test to confirm that it is finding first

IndexFile.GetByNameAndVersion -> IndexFile.FindFirst with Tests

---

pkg/engine/task/podexec/pod_exec.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/update.go
pkg/kudoctl/http/http_client.go
pkg/kudoctl/packages/reader/reader_tar.go
pkg/kudoctl/packages/writer/writer_tar.go
pkg/kudoctl/util/repo/digest.go
pkg/kudoctl/util/repo/index.go
pkg/test/harness.go
pkg/test/utils/kubernetes.go

This changes fmt.Printf to clog.Printf since the former does not produce a trailing newline.
Fixes #1267

Fix trailing newlines when printing errors.

---

pkg/kudoctl/util/kudo/kudo.go

Otherwise we're printing empty strings. See the referenced issue.
Fixes #1279

Populate GVK in objects fetched from API server.

---

pkg/test/utils/kubernetes.go

We are calling WaitForCRDs with two types of arguments, but so far were
only handling one of them, and silently ignoring the unstructured
objects. In this latter case, this function was effectively a no-op.
Fixes #1282

Make WaitForCRDs work with Unstructured arguments.

---

pkg/kudoctl/cmd/verify/verify.go
pkg/kudoctl/cmd/verify/verify_test.go

Fix https://github.com/kudobuilder/kudo/issues/1266.
But currently, we do not compare `kubernetesVersion` with `apiserver`. Only the `kubernetesVersion` in the `operator.yaml` is verified.

Verify kubernetesVersion when run 'package verify'.

---

pkg/kudoctl/cmd/generate/plans.go

if plans are missing from operator yaml it results in a nil map.  no joy.  this fixes that.

Bugfix: No Panic for Missing Map of Plans

---

.golangci.yml
pkg/engine/renderer/enhancer.go
pkg/engine/task/task_pipe_test.go
pkg/engine/task/task_test.go
pkg/kudoctl/cmd/init_test.go
pkg/kudoctl/cmd/repo_index_test.go
pkg/kudoctl/env/environment_test.go
pkg/kudoctl/http/http_client_test.go
pkg/kudoctl/kudoinit/setup/wait.go
pkg/kudoctl/packages/reader/reader_test.go
pkg/test/case_test.go
pkg/test/harness.go
pkg/test/step.go
pkg/test/step_test.go
pkg/test/utils/kubernetes_test.go
pkg/version/version_test.go

'scopelint' checks for unpinned variables in 'range'-loops. This helps to avoid subtle bugs.
'unconvert' checks for unnecessary type conversions.

Enable the 'scopelint' and 'unconvert' linters

---

pkg/engine/renderer/parser.go
pkg/engine/renderer/parser_test.go

I wonder how we got away with splitting on *any* three dashes for so
long.
Fixes #1297

Fix YamlToObject file splitting.

---

pkg/kudoctl/packages/resolver/resolver.go

Fixes #1269 
Print detailed error when `resolver` cannot find the specific package or version.
1. When install a non-existent operator version:
```
Error: failed to resolve operator package for: kafka resolver: unable to find packages for kafka
Error: failed to resolve operator package for: kafka getting kafka in index file: no operator version found for kafka-8.0.0
```
2. When install a non-existent package
```
Error: failed to resolve operator package for: non-exist resolver: unable to find packages for non-exist
Error: failed to resolve operator package for: non-exist getting non-exist in index file: no operator found for: non-exist
```

Print detailed error when installing package.

---

pkg/engine/task/task_apply.go
pkg/engine/task/task_apply_test.go

Summary:
Fixes #1288
Fixes #1265

Proper handling of cluster-scoped resources in operators

---

pkg/kudoctl/cmd/update_test.go

Original code:
```
if err != nil {
if !strings.Contains(err.Error(), tt.errMessageContains) {
t.Errorf("%s: expected error '%s' but got '%v'", tt.name, tt.errMessageContains, err)
}
} else if tt.errMessageContains != "" {  
t.Errorf("%s: expected no error but got %v", tt.name, err)
```
Here err is nil but tt.errMessageContains is not nil. So the error logging should be fixed

Fix error logging in kudo-cli test

---

pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_test.go

Corrects the calculation if a reconcile should be done for DeleteEvents.
The comment in the code states that it should be skipped for PipePods, but at the moment it triggers reconciles ONLY for PipePods.
Fixes #1321

Fixed calculation of reconcile event handling for PipePods

---

cmd/manager/main.go
pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_test.go
pkg/engine/task/task.go
pkg/engine/task/task_pipe.go
pkg/engine/workflow/engine.go
pkg/engine/workflow/engine_test.go
pkg/test/harness.go

Plumb the config through alongside the client object (since they convey
the same information really) all the way to pipe task.
This way we use the same explicit config everywhere, rather than rely on
config.GetConfig to guess the correct one. This is especially important
when running the controller outside of a cluster.
Fixes https://github.com/kudobuilder/operators/issues/205

Plumb rest config through from manager.

---

pkg/engine/renderer/enhancer.go
pkg/engine/renderer/parser.go
pkg/engine/renderer/parser_test.go

This is to avoid splitting the YAML file "by hand" and instead use
provided libraries.
Something like this was suggested in review of #1298 (in turn provoked by #1297 ).
Also, this
Fixes: #1331

Refactored YamlToObject.

---

pkg/engine/renderer/engine.go
pkg/engine/renderer/engine_test.go
pkg/engine/task/render.go
pkg/kudoctl/cmd/verify/verify.go
pkg/kudoctl/packages/verifier/template/verify_render.go
pkg/kudoctl/packages/verifier/template/verify_render_test.go
pkg/kudoctl/packages/verifier/template/verify_template_render.go

Render the templates as part of the `package verify` command so we catch expression errors.
Fixes #1301

Add RenderVerifier for templates

---

pkg/apis/kudo/v1beta1/instance_types.go
pkg/controller/instance/instance_controller.go
pkg/kudoctl/cmd/testdata/invalid-params.golden
pkg/kudoctl/cmd/testdata/invalidzk/params.yaml
pkg/kudoctl/cmd/verify/verify.go
pkg/kudoctl/packages/verifier/plan/verify_references.go
pkg/kudoctl/packages/verifier/plan/verify_references_test.go

Verify plans are referenced and referenced plans are defined
Fixes #1268

Error out in instance controller when a parameter has an undefined plan trigger

---

pkg/kudoctl/util/kudo/install.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go

Add unit tests to verify that.
Add message if operator version install does not install new version
Fixes #615

Compare real operator name, not prefix when checking for installed versions

---

pkg/apis/kudo/v1beta1/instance_types.go
pkg/kudoctl/cmd/package_verify_test.go
pkg/kudoctl/cmd/testdata/invalid-params.golden
pkg/kudoctl/packages/verifier/plan/verify_references.go
pkg/kudoctl/packages/verifier/plan/verify_references_test.go

Summary:
- removed verifying that a plan is not referenced by any parameter. In the light of upcoming KEP-18 allowing triggering plans manually, some plans e.g. `backup` won be referenced by any parameter
- added verifying that at least `deploy` plan exists in the operator

Plan verifier checks for mandatory `deploy` plan

---

pkg/webhook/instance_admission.go
pkg/webhook/instance_admission_test.go

Summary:
This is a followup to #1336 which verified that triggered plans are actually defined in the OV. This PR adds this logic to the instance webhook.
Fixes #1268

Error out in instance webhook when a parameter has an undefined plan trigger

---

pkg/kudoctl/packages/reader/parser.go
pkg/kudoctl/packages/reader/parser_test.go
pkg/kudoctl/packages/reader/read_dir.go

Use full filename and path to check for operatorFile and paramsFile 

---

pkg/controller/instance/instance_controller.go

This ensure that cleanup plans aren't (re-)started after a fatal error.
Fixes #1357

Explicitly cover only specific plan status for cleanup plans

---

Makefile
pkg/kudoctl/packages/verifier/template/verify_render.go
pkg/kudoctl/packages/verifier/template/verify_render_test.go

Fix makefile if PATH does not include GOPATH/bin

Verify that a rendered template is valid YAML

---

pkg/engine/task/task_apply.go
pkg/engine/task/task_delete.go
pkg/engine/task/task_pipe.go
pkg/test/utils/subset.go
pkg/util/kudo/labels.go
test/integration/remove-pod-container/00-assert.yaml
test/integration/remove-pod-container/00-errors.yaml
test/integration/remove-pod-container/00-install.yaml
test/integration/remove-pod-container/01-assert.yaml
test/integration/remove-pod-container/01-update.yaml
test/integration/remove-pod-container/02-assert.yaml
test/integration/remove-pod-container/02-errors.yaml
test/integration/remove-pod-container/02-update_param.yaml
test/integration/remove-pod-container/dual-pod-operator/operator.yaml
test/integration/remove-pod-container/dual-pod-operator/params.yaml
test/integration/remove-pod-container/dual-pod-operator/templates/deployment.yaml

The ApplyTask patch method currently uses a StrategicMerge patch, which by default merges some lists, for example, containers in a Deployment-PodTemplate. This makes it impossible to have a conditional container in an operator.
Added a test harness test.
Fixes #1286 
**Issue**
The Big Problem is that applying new versions of rendered resources from KUDO to the cluster is not as easy as it seems: We generally render full resources from the `OperatorVersion` templates, but there is no easy way to update existing resources in the cluster:
**Patch with StrategicMerge**
This is the solution we use at the moment. The issue is, that a strategic merge does not replace certain lists - for example, the list of containers in a PodTemplate is merged, not …

Fix `ApplyTask` patch behavior

---

pkg/controller/instance/instance_controller.go

Summary:
We check `IsFinished` and **not** `IsTerminal` status condition for the `cleanup` plan so that the finalizer is not removed in the `FatalError` case. This way a human operator has to intervene and we don't leave garbage in the cluster.

Remove the Instance finalizer only if the `cleanup` plan was successfully finished

---

go.mod
go.sum
hack/update_codegen.sh

This is implementing a workaround as discussed in
https://github.com/kudobuilder/kudo/pull/1326
The logic in update-codegen.sh is changed to deal with the replace.
We can just remove the replace once we upgrade to upstream
code-generator which has the change, i.e.
v0.18.0-alpha.1.0.20191220033320-6b257a9d6f46 or later.

Use a fork of code-generator.

---

Makefile
pkg/kudoctl/cmd/package_list_params_test.go
test/README.md

Signed-off-by: Zain Malik <zmalikshxil@gmail.com>
Updating the golden files for tests wasn't documented and for first time contributors to those it can be hard to discover how to do it.
This PR adds a Make target to update golden files, and requires the name of individual test to update only one by one. This is to address concerns to avoid doing a massive update in golden files by error
examples: 
```
make update-golden-TestInitCmd_dry
make update-golden-TestParamsList
```

chore: add target to update golden-files for individual tests

---

keps/0025-template-to-yaml-function.md
keps/20200225-template-to-yaml-function.md

This KEP describes addition of a function called `toYaml` for use in the operator templates.

[KEP 0025] Template toYaml function

---

keps/0024-parameter-enhancement.md

This KEP aims to improve the use-cases that can be covered by parameters. By supporting additional types, templates can access lists and dictionaries. Furthermore, validation can be implemented for known types.
As needed by #1349, #988, #951 
Related: #1221; this KEP would allow to iterate over the items of a dict to create YAML, but having a `toYAML` template function would still be beneficial

KEP-24: Enhanced Operator Parameters

---

hack/install-golangcilint.sh

Upgrade to the latest release of `golangci-lint`.

Bump golangci-lint to 1.23.7

---

CONTRIBUTING.md
Makefile

Make lint work without a $GOPATH.
Also document the need for $GOBIN to be in developer's $PATH.
Fixes #1373

Make lint work without a $GOPATH.

---

.github/release-drafter.yml

The release on master is targeted to be a minor release not a patch release.
Releases on release branches (releases/0.10) are targeted for a patch release (and we will need to remember to update this when a release branch is created)
The details of docker is removed because:
1. in the process of release notes being added this information is false
2. when we release (currently) it is with goreleaser which will provides this information.   The goreleaser info and this info will need to be manually merged at the end of the release process.

updating to be consistent with our release process

---

pkg/engine/health/health.go
pkg/engine/task/task.go
pkg/engine/task/task_apply.go
pkg/engine/task/task_pipe.go
test/e2e/terminal-failed-job/00-assert.yaml
test/e2e/terminal-failed-job/00-install.yaml
test/e2e/terminal-failed-job/01-assert.yaml
test/e2e/terminal-failed-job/01-install-timeout.yaml
test/e2e/terminal-failed-job/failjob-operator/operator.yaml
test/e2e/terminal-failed-job/failjob-operator/params.yaml
test/e2e/terminal-failed-job/failjob-operator/templates/failjob.yaml
test/e2e/terminal-failed-job/job-timeout-operator/operator.yaml
test/e2e/terminal-failed-job/job-timeout-operator/params.yaml
test/e2e/terminal-failed-job/job-timeout-operator/templates/timeoutjob.yaml

At the moment, the TaskApply waits for all resources to become healthy. Healthy for a job is defined as `Successful`. But there are jobs which may never reach that state, as they fail and reach their `backOfLimit`.
KUDO should acknowledge this and set the task to a FATAL_ERROR so the user gets a feedback and a different job can be executed.
Fixes #1367

Fatal error on terminal job

---

keps/0000-kep-template.md

I can see why we might mark it "implemented" if we consider this document itself a KEP, however the other fields are mostly fillers as well, so I think it makes sense to mark it provisional by default since a new KEP will always be provisional.

Mark the status in the kep-template provisional

---

pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/plan/plan_status.go
pkg/kudoctl/cmd/plan/plan_status_test.go

Alphabetise (by plan) the output of the plan status and history commands so that they're consistent with each run.  This helps human operators when monitoring a deployment.
Fixes #1354

Sort output of plan status and history commands

---

pkg/controller/instance/instance_controller.go
test/e2e/cli-install-uninstall/02-errors.yaml

Summary:
we save one `Update` call in the `instance_controller.go::updateInstance` method by removing the finalizer **before** updating the instance. To avoid misleading log messages, the subsequent updating of the status is handling the fact that the instance might be removed.

Simplify instance update code

---

pkg/controller/instance/instance_controller.go

Only try to remove finalizers if we're actually in the deletion process

Cleanup finalizer removal in instance update

---

keps/0023-enable-disable-features.md
keps/README.md

Signed-off-by: Zain Malik <zmalikshxil@gmail.com>
Just update the KEP-23 status as we discussed in sync

Update the KEP-23 status

---

Makefile
test/README.md

Update to https://github.com/kudobuilder/kudo/pull/1369
There seemed to be a concern of "massive updates" which doesn't make sense to me.
The requirement to know all tests and manually type each in or copy and paste them is an unnecessary burden on the developer IMO.   Updating the entire project will update all affected files.   If there is a file that was updated that is a surprise to the developer they should investigate before pushing a PR.  Additionally any file that changed that was NOT updated would have failed any tests anyway.  Lets make it easier on us please.

Update golden files the easy way

---

pkg/apis/kudo/v1beta1/instance_types_helpers.go
pkg/controller/instance/instance_controller.go

Co-Authored-By: Andreas Neumann <aneumann@mesosphere.com>
Co-Authored-By:  Ken Sipe <kensipe@gmail.com>

Making finalizer removal even more readable

---

keps/0009-operator-toolkit.md
keps/0010-package-manager.md

This PR now is consist with the Go Struct changes in https://github.com/kudobuilder/kudo/pull/863
It removes the controversial schema notation which will be add back in later.   Please look with a new set of eyes.
DETAILS FROM ORIGINAL PR BELOW
1. Expose full details of what is available to an operator developer.  Previously a user was required to look at examples and source code to have full knowledge of what was possible in operator, params, and index yaml files
2. Provide a basis for tech discussion around the richness of the model.  To find gaps in expression and requirements.  To unify the mental model around this and provide a firm target for v1.
3. To clean up the keps, as the TOCs were incorrect.  There is still more clean necessary but it …

KEP-9 and 10 Updates which includes all possible user facing YAML possibilities

---

pkg/engine/renderer/enhancer.go
pkg/engine/renderer/parser.go
pkg/engine/renderer/parser_test.go

As described in #1397, large templates would cause package verification to fail. This is fixed by using the old approach of splitting input YAML in `YamlToObject`.
Note for reviewers:
Manually tested that `kubectl kudo package verify` works with the spark operator in the community repository. Merging https://github.com/kudobuilder/operators/pull/153 will make sure that this operator is tested with every PR against KUDO.
Fixes #1397

Fix decoding errors with large YAML templates

---

pkg/engine/renderer/enhancer.go
pkg/kudoctl/packages/verifier/template/verify_render.go
pkg/kudoctl/packages/verifier/template/verify_render_test.go

[This example](https://github.com/kudobuilder/kudo/issues/1397#issuecomment-596350829) shows why the current message is not verbose enough.

Mention template filename in error message.

---

CONTRIBUTING.md

Manager no longer is a deployment

---

pkg/kudoctl/packages/writer/writer_test.go

The `os.Open` calls were always returning a nil and an error, so the
test was joyfully comparing that nil==nil.
This highlights the importance of *not* ignoring errors.

Fix tar test.

---

pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_test.go
pkg/kudoctl/packages/verifier/template/verify_render.go
pkg/kudoctl/packages/verifier/template/verify_render_test.go

Collect keys from all pipetasks and feed that to template rendering in place of
an empty map. This has lots of room for improvement, but at least does not fail
on every single package which uses Pipe tasks.
Fixes #1398

Teach package verifier about pipe tasks.

---

keps/0024-parameter-enhancement.md
keps/0026-reading-parameter-values-from-a-file.md
keps/README.md

Update some KEP metadata and list.

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/util/kudo/install.go
pkg/kudoctl/util/kudo/install_test.go

* work in progress, not working yet
* the idea to have the status call returns something is there, but I guess the "something" needs to be reworked
Attempt to solve #964 
Fixes #964

Add the --wait flag to install

---

pkg/controller/instance/instance_controller.go
pkg/engine/health/health.go
pkg/engine/renderer/enhancer.go
pkg/engine/task/render.go
pkg/engine/task/task_apply.go
pkg/engine/task/task_apply_test.go
pkg/engine/task/task_delete.go
pkg/engine/task/task_delete_test.go
pkg/engine/task/task_pipe.go
pkg/engine/types.go

Summary:
previously any error returned by the `Enhancer` was treated as fatal. It made sense because it would act deterministically on a prepared set of resources. However, since #1319 enhancer also uses the discovery interface to determine whether or not the given resource is namespaced. These API requests may fail and must be retried. With this fix, `DefaultEnhancer` clearly marks certain errors as fatal.
Fixes #1413

Enhancer and HealthUtil now differentiate between fatal and transient errors

---

hack/update_kep_overview.sh
keps/0017-pipe-tasks.md
keps/0023-enable-disable-features.md
keps/0024-parameter-enhancement.md
keps/0025-template-to-yaml-function.md
keps/0026-reading-parameter-values-from-a-file.md
keps/README.md

Update the status to match reality.
This also adds some icons to the list - instant visual cue about the
individual and overall status.

Update some KEP status and refresh the list.

---

go.mod
go.sum
pkg/kudoctl/cmd/params/parser.go
pkg/kudoctl/cmd/params/parser_test.go

Turns out that [`yaml.v2` unmarshals maps into `map[interface{}]interface{}`](https://github.com/go-yaml/yaml/issues/139) rather
than try to insist on a most narrow possible key type (i.e. string). Such values
are then rejected by sigs.k8s.io/yaml.Marshal that `WrapParamValue` uses,
because it does a conversion to JSON first, and JSON does not support
non-string keys.
It seems like `yaml.v3` works better in that regard. However comments on the
aforementioned issue seem to imply that it's still not all rosy.
Moreover, using the same package for unmarshalling as we do for marshalling
seems like a more stable choice long-term.
This also adds some vlog statements and tidies up go.mod.
Fixes #1437

Use sigs.k8s.io/yaml rather than pkg.in/yaml.v2.

---

Makefile

Previously there was a check to see if controller-gen was missing, then it installed the version associated with controller tools.  Now it actually checks to see if this is the correct version otherwise gets the correct version.
I looked at doing the same for `go-bindata` but it's version output is challenging and likely needs `awk`.   This makes controller-gen much better which is the more likely change.

Check Controller-gen Version

---

Makefile
hack/install-golangcilint.sh
pkg/kudoctl/cmd/verify/verify_test.go

bump to latest go lint, which catch unnecessary code.  added a better check to ensure that all devs are on the latest

 golangci-lint upgrade

---

keps/0000-kep-template.md
keps/0004-add-testing-infrastructure.md
keps/0012-operator-extensions.md
keps/0013-external-specs.md
keps/0015-repository-management.md

found linter and was going to include it in our makefile.. but it has some issues I don't think we want to deal with yet.
The Makefile change would be:
```
.PHONY: doc-lint
doc-lint:
ifeq (, $(shell which liche))
go get github.com/raviqqe/liche
endif
liche -r .
```
The issue is it gets rate limited on GH.  I've reported an issue on the project: https://github.com/raviqqe/liche/issues/37
This PR contains some changes based on using the tool to the extent that I could.  There are also several bugs filed for things I'm not aware of how to fix.

Docs Linted

---

pkg/apis/kudo/v1beta1/instance_types_helpers.go

Summary:
we were resetting `Status.AggregatedStatus.ActivePlanName` field when the plan was terminal. This lead to this field looking like this:
```
Status:
Aggregated Status:
Status:  COMPLETE
```
The idea of the field is to keep information about the last/current plan including plan name and status.

Keep plan name in instance aggregatedStatus when plan is terminal

---

Makefile
hack/install-golangcilint.sh

golangci-lint v1.24.0 seems to have memory issues resulting in CI failure on circleci, which we are limited to 4GB without a paid for account.
these issues do not exist in v1.23.8

golangci-lint memory issue fix

---

pkg/kudoctl/packages/verifier/template/parser.go
pkg/kudoctl/packages/verifier/template/verify_parameters_test.go

After fixing this I was hesitate to call this a bug as recorded... since it is documented as `// no support for Range, Template or TextNodes` :)   We didn't document that outside of code and it is worth having this feature (and needed for our kafka operator).  Thanks @zmalik for being awesome and reporting this.
`kudo package verify` now supports range.  Tests provided.
Fixes #1432

Package Verify Support for Template Range

---

Makefile

If the respective binaries aren't available in '$PATH', this will no longer be printed out. Due to the way Makefiles work, this would have been printed even when using targets that don't depend on these version checks (e.g. when running 'make cli-fast').
Fixes some irritating warnings that might occur on unrelated make targets

Silence failing version checks

---

pkg/kudoctl/cmd/testdata/invalid-params.golden
pkg/kudoctl/cmd/verify/verify.go
pkg/kudoctl/cmd/verify/verify_test.go

we should be verifying all the versions
AND provide better messaging... if the version is missing, it should be clear
additionally the name of the 2nd test around this looked to be a copy+paste error, it had the same name as the 1st test and it was an incorrect name for the test.
Fixes #1419

Package Verify of Versions

---

pkg/kudoctl/cmd/root.go
pkg/kudoctl/cmd/search.go
pkg/kudoctl/cmd/search_test.go
pkg/kudoctl/cmd/testdata/index.yaml
pkg/kudoctl/cmd/testdata/merge-index.yaml.golden
pkg/kudoctl/cmd/testdata/search1.golden
pkg/kudoctl/cmd/testdata/search2.golden
pkg/kudoctl/cmd/testdata/search3.golden
pkg/kudoctl/util/repo/repo_operator.go
pkg/kudoctl/util/repo/resolver_repo.go
pkg/kudoctl/util/repo/resolver_repo_test.go

KUDO search for Operators
*new command*: `kudo search <fo>`
Provides ability to search for operators in the repository.
The search is a "contains" in the name of the operator and does not require a `*`
By default it returns the firstMatch based on install criteria, which means the result will be any match with operator and app version that is "current"
```
go run cmd/kubectl-kudo/main.go search kafka
Name 	Operator Version	App Version
kafka	1.2.0           	2.4.0    
```
It is possible to get all the versions with `-a` flag
```
go run cmd/kubectl-kudo/main.go search kafka -a
Name 	Operator Version	App Version
kafka	1.2.0           	2.4.0      
1.1.1           	2.4.0      
1.1.0           	2.4.0      
1.0.2           	2.3.1      
1.0.1           	2.3.1      
1.0.0           	2.3.0 …
```

Man's Search for Operators

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/plan/plan_status.go
pkg/kudoctl/cmd/plan/plan_wait.go
pkg/kudoctl/util/kudo/install.go
pkg/kudoctl/util/kudo/install_test.go
pkg/kudoctl/util/kudo/kudo.go

@anthonydahann a community member made the first PR to introduce `--wait` to install.
As outlined in the issue #1418 there is a desire to move this code into a reusable space (not the CLI) with a request to add it into `kudoClient`.  This enables the ability to use kudo as a library from terraform in particular for https://github.com/kudobuilder/terraform-provider-kudo.  `WaitForInstance` in kudo.go now provides this ability.
After modifying `kudo install` to use this wait, it made sense to add a `wait-timeout` for client control.  This is super important as it is very unclear how long a plan will take to "finish".
The challenge from a user perspective at that point is what if the `timeout` expired and you want to wait again... or what if you didn't wait but now you want to.   It just …

Waiting For a Plan to Finish

---

.goreleaser.yml

`skip_push: auto` means that goreleaser will not push to docker for rc releases and will push for full releases.  Our process expects RC images.
details from [docs](https://goreleaser.com/docker/)
```
skip_push: false
```
The default is false, which is what we want... 
Fixes #1466

Always Docker Push on Release Including RC

---

.goreleaser.yml

Better solution to #1468 
The solution here is to always push the release tag (even if it is an RC release) but to only bump the `:latest` tag for full releases.
Fixes #1466

Docker publishing updates

---

keps/0022-diagnostics-bundle.md
keps/README.md

KEP-22: Add initial design on diagnostics bundles

---

keps/0029-operator-dependencies.md

This KEP aims to improve operator user and developer experience by introducing operator dependencies.
Co-authored-by: Marcin Owsiany <marcin@owsiany.pl>

KEP-29: Operator dependencies

---

pkg/webhook/instance_admission.go
pkg/webhook/instance_admission_test.go

if the `deploy` plan is triggered by the update. This seems to be a reasonable exception since the `deploy` plan is used for upgrades in many cases anyway.

Allow simultaneous upgrade and parameter update

---

pkg/kudoctl/env/environment.go
pkg/kudoctl/kube/config.go

Use the namespace defined in the current context, if it's been set.
Otherwise default to 'default'.
Signed-off-by: Nick Jones <nick@dischord.org>
Fixes #1477

fix: Use namespace specified by current config context

---

pkg/engine/renderer/consts.go
pkg/engine/renderer/dependencies.go
pkg/engine/renderer/dependencies_test.go
pkg/engine/renderer/enhancer.go
pkg/engine/renderer/enhancer_test.go
pkg/test/fake/client.go

Adding labels/annotations in all possible paths and relying on conversion to typed objects to remove invalid paths obviously only works for resources where we have the typed objects available. For almost all CRDs this leaves the resources with unwanted labels and annotations in multiple locations.
We now have custom lists for locations based on the G(V)K.
Fixes #1498

Apply labels and annotations only in the correct paths

---

hack/run-e2e-tests.sh
pkg/kudoctl/cmd/init.go
pkg/kudoctl/kudoinit/manager/manager.go
pkg/kudoctl/kudoinit/options.go

This makes it easier to deploy KUDO in test environments where a KUDO image is available in the cluster but not in any repository.

Allow to override the pull policy of the controller in 'kudo init'

---

keps/0031-namespace-management.md

KEP-31: Namespace Management

---

cmd/manager/main.go
pkg/webhook/instance_admission.go
pkg/webhook/instance_admission_integration_test.go

Summary:
we've seen increased flakiness lately with some ITs e.g. `terminal-failed-job` and `dependencies-hash` where a previously created `OperatorVersion` is not observed by the instance admission webhook. This PR switches to an uncached client for the IAW which should alleviate the problem.

Uncached client for instance admission webhook

---

pkg/engine/renderer/dependencies.go
pkg/engine/renderer/dependencies_test.go
pkg/engine/renderer/enhancer_test.go
test/e2e/dependencies-hash/01-assert.yaml
test/e2e/dependencies-hash/02-assert.yaml
test/e2e/dependencies-hash/04-assert.yaml
test/e2e/dependencies-hash/06-assert.yaml

The easiest fix for the referenced issue is to simply ignore resources that are reported as "NotFound" from the API server. The deployment/statefulset/etc can still be applied, and k8s will correctly use the referenced config maps/secrets as soon as they are available, therefore not blocking KUDO.
The downside is that the next time the deployment/statefulset/etc gets deployed the hash changes and triggers a pod reload, but I think that's an acceptable downside.
Additionally, we can't rely on the `LastAppliedTemplateAnnotation`, as this annotation is only available on resources deployed by KUDO. We may encounter references that are applied either manually or by other controllers that don't have this annotation. 
The fix for this is to fall back to …

Skip resources that are NotFound for dependency calculation

---

pkg/engine/workflow/engine.go

Summary:
previously, building a task would only fail for `UnknownTaskKind` reason. However, we're past that and have more error reasons e.g. validation. For now, the reason is kept generic, but we might revisit this should the need arise.

Rename `UnknownTaskKind` to `TaskBuildError`

---

hack/verify-generate.sh

I had a recent fight with CI over "verifying" codegen.   This was due to a homebrew update of go-bindata which was out of sync with the CI env.   It was more challenging than it needed to be and this information in our CI logs would have made it easy.

Add Tool Gen version Info to output for CI

---

pkg/kudoctl/cmd/verify/verify.go
pkg/kudoctl/packages/verifier/template/verify_namespace.go
pkg/kudoctl/packages/verifier/template/verify_namespace_test.go
pkg/kudoctl/packages/verifier/template/verify_references.go

Package Verify now includes namespace checks
1. No `kind: Namespace` allowed in an operator
2. namespace manifest is specified must exist, must be 1 manifest in the yaml file, it must be `kind: Namespace`
Fixes #

Namespace Package Verify

---

pkg/engine/renderer/engine.go
pkg/engine/task/render.go
pkg/kudoctl/packages/verifier/template/verify_render.go
pkg/kudoctl/util/kudo/install.go
pkg/kudoctl/util/kudo/install_test.go
pkg/kudoctl/util/kudo/testdata/namespace.yaml
pkg/kudoctl/util/kudo/testdata/rendered-namespace.yaml.golden

KEP31: Template Support for Namespace Manifest

---

pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/plan/plan_trigger.go
pkg/kudoctl/cmd/update.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go
pkg/kudoctl/util/kudo/upgrade.go

`--wait` and `--wait-time` added for `plan update` and `plan trigger`

Plan Update and Trigger with Wait

---

.circleci/config.yml
Makefile
hack/run-e2e-tests.sh
hack/run-operator-tests.sh
test/Dockerfile
test/run_tests.sh

This runs operator tests as a separate test in parallel with the other tests. It makes operator tests independent from E2E test results and their failures distinguishable.
Fixes #1539

Separate E2E and operator tests

---

pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go

If a namespace was created without a manifest, KUDO would fail with a segfault, because it tries to add an annotation to a nil map. This has been fixed and tests have been added for namespace creation.

Fix namespace create without manifest

---

pkg/engine/renderer/enhancer.go

Summary:
`controller-runtime` already validates the [namespace ownership rules](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L144) which was presumably not always the case (and why we had to implement our own).

Remove obsolete `setControllerReference` method

---

pkg/apis/kudo/v1beta1/instance_types_helpers.go
pkg/apis/kudo/v1beta1/instance_types_helpers_test.go
pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_test.go
pkg/webhook/instance_admission.go

Summary:
current instance controller reconciliation logic with regard to detecting currently active plan can be much simpler now that we have IAW (instance admission webhook) controlling the scheduled plan.

Simplify instance controller reconciliation

---

pkg/engine/renderer/enhancer.go
pkg/engine/renderer/enhancer_test.go
pkg/engine/resource/object_key.go
pkg/engine/task/render.go
pkg/engine/task/task_apply.go
pkg/engine/task/task_apply_test.go
pkg/engine/task/task_delete.go
pkg/engine/task/task_delete_test.go
pkg/engine/task/task_pipe.go
pkg/engine/workflow/engine_test.go

For the `DeleteTask` and `ToggleTask` we use the enhance process - but this fails when the resource to delete is a custom resource for a CRD which is not installed in the cluster. This is especially problematic for the `ToggleTask` which is often used to guard deployment of features.
We need to filter the rendered templates - If one of them is of an unknown type, we shouldn't try to delete it as it can't be there anyway.
This PR splits the convert functionality from the enhancer and skips enhancing for the DeleteTask, then filters the resources for unknown types
Fixes #1547 

Filter unknown custom resources in Delete- and ToggleTask

---

pkg/apis/kudo/v1beta1/instance_types.go
pkg/apis/kudo/v1beta1/instance_types_helpers.go
pkg/controller/instance/instance_controller.go
pkg/engine/task/task_kudo_operator.go
test/integration/operator-with-dependencies/01-assert.yaml

KEP-29: instance controller reconciliation for parent instances

---

go.mod
go.sum
pkg/apis/kudo/v1beta1/operatorversion_types_helpers.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/packages/install/dependencies.go
pkg/kudoctl/packages/install/dependencies_test.go
pkg/kudoctl/packages/install/package.go
pkg/kudoctl/packages/install/package_test.go
pkg/kudoctl/packages/resolver/resolver.go
test/integration/operator-with-dependencies/01-install.yaml
test/integration/operator-with-dependencies/parent-operator/operator.yaml

When installing an operator package using the KUDO CLI, operator dependencies can be provided as _KudoOperator_ tasks. For each of these tasks, the respective package is resolved and its `Operator` and `OperatorVersion` installed on the cluster. Because dependent package can also have dependencies on packages, dependencies are resolved recursively. Cyclic dependencies are detected by modeling the dependencies as a directed graph and checking this graph for cycles when new dependencies are added.
Fixes part of #1514
Co-authored-by: Aleksey Dukhovniy <adukhovniy@mesosphere.io>

KEP-29: Install dependencies of operators.

---

pkg/kudoctl/packages/install/dependencies.go
pkg/kudoctl/packages/install/dependencies_test.go
pkg/kudoctl/packages/install/package.go
test/integration/operator-with-dependencies/01-assert.yaml
test/integration/operator-with-dependencies/parent-operator/operator.yaml

Package dependencies can reference operator packages from local files or arbitrary URLs. KUDO's controller doesn't know about the origin of packages once they have been resolved. But it needs to resolve instances from `KudoOperator` tasks. To solve this, the `Package` and `OperatorName` of these tasks are updated with the operator name before they are applied on a cluster.

Set operator name of 'KudoOperator' tasks for dependencies

---

Makefile
pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init_integration_test.go
pkg/kudoctl/cmd/init_test.go
pkg/kudoctl/cmd/testdata/newop/operator.yaml.golden
pkg/kudoctl/kudoinit/options.go
pkg/version/version.go

This hopefully should have no impact on developer workflows nor on how a (pre-)released build works. However in cases where a matching controller docker image does not exist, it will fail fast, rather than deploying a (potentially incompatible) controller from a docker image built for some earlier commit.
Implementation:
- first, set `pkg/version.gitVersion` to a version string using `$LDFLAGS` only when a tagged commit is checked out (this will always be true for release builds). In other cases, set it to a sentinel value.
- then refuse to `kudo init` unless the sentinel value is overridden explicitly.
Fixes #1549 

Fail kudo init if version is unknown.

---

pkg/controller/instance/instance_controller.go
pkg/controller/instance/resolver_incluster.go
pkg/engine/task/task_kudo_operator.go
pkg/kudoctl/resources/install/operator.go
test/integration/operator-with-dependencies/01-assert.yaml

Summary:
after updating the [flink-demo](https://github.com/kudobuilder/operators/pull/279) to use dependencies a few fixes were needed:
- instance controller now properly reconciles (parent) instances owning child instances
- `InClusterResolver` ignores operators `appVersion` if it wasn't set
- child instance names are generated differently:
- if the `instanceName` was set, it is taken without modifications
- otherwise, `parentInstance-childOperator` is taken e.g. `kafka-zookeeper`. in this case, we also use `-` instead of `.` separator since instance names are often used as service names (DNS-1035 label) which only allow alphanumeric characters or `-` in them.

Reconcile parent instances when a child instance is done

---

pkg/kudoctl/util/kudo/kudo.go

comparable functionality to checking Operator.

Add helper function to check if OV exists in cluster

---

pkg/kudoctl/cmd/test.go

Adding Test Reports Feature

---

test/README.md

* Fixes a typo
* Changes some grammar
* Makes cert generation a single command (instead of answering a series of questions)
* Adds notes and tips
I'm very interested in making this easier... but this is step 1.

Updates to local run

---

pkg/kudoctl/cmd/install.go
pkg/kudoctl/packages/resolver/resolver.go

Please read #1557 for full context.   There has been confusion around specifying an operator name which is the same name as a folder in the CWD.  The issue makes a lot of sense.  There were a number of suggestions including sending details to STDOUT.
I'm not a fan of noisy CLIs... the information is there if you increase verbosity (`-v=2`).
The biggest issue is that if there is a folder with the same name as an operator, it is assumed to be what the user wants... all that was previously necessary is that `fs.Stat(name)` passes..  If this condition exists,  there is no attempt to go to a repo etc.
The change makes necessary to specify a local operator with more than just a name... if it is in the CWD than `install ./foo` or `install ./foo.tgz` is necessary.  It requires that more than the …

Installing Local Operators Requires Abs or relative notation

---

hack/generate_krew.sh

Our release process removed the 32-bit darwin several releases ago... but the krew files still referenced it and needs to be removed.

Darwin 32-bit is not supported any longer

---

README.md
development.md

Adding a development.md with a link from the project readme.
This is consistent with kube community approach.  Example:  https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#building-kubernetes-on-a-local-osshell-environment

Development Readme

---

pkg/kudoctl/packages/convert/resources.go

There's no need for this log - it might confuse people that this is something they need to fix or adjust. Maybe we should add a warning in the `package verify` if a Dummy Task is used, as it should be only used for debugging though.

Don't log anything when validating dummy task

---

pkg/kudoctl/cmd/diagnostics.go

Currently it is not required and yields the following error:
```
./bin/kubectl-kudo diagnostics collect
Collect Logs for 1 pods
Error: failed to get instance default/: resource name may not be empty
```

Mark instance as required parameter for diagnostics

---

pkg/kudoctl/cmd/diagnostics.go
pkg/kudoctl/cmd/diagnostics/diagnostics.go
pkg/kudoctl/cmd/diagnostics/diagnostics_test.go
pkg/kudoctl/cmd/diagnostics/print.go
pkg/kudoctl/cmd/diagnostics/runner_helper.go

Allow `kudo diagnostics collect --outputDir instance1` so we can collect multiple diagnostics in the same directory

Allow custom output directory for diagnostics collection

---

pkg/kudoctl/cmd/generate/operator.go
pkg/kudoctl/cmd/package_new.go
pkg/kudoctl/cmd/package_new_test.go
pkg/kudoctl/cmd/prompt/operator.go
pkg/kudoctl/cmd/testdata/newop/operator.yaml.golden

After starting prototyping on a new operator I stumbled over `kudo package new` - this PR improves a bit. I'm open for discussions, but this feels a lot better to me:
- When `kudo package new` finishes, print a message and let the user know about `kudo package add parameter` etc. I didn't know it/forgot about it.
- When `kudo package new` is called without params, let the user know about the "-i". (Because that's an amazing feature, but hard to find if you don't know about it)
- Allow `kudo package new` to be called with either an operator name, or `-i` - in interactive mode the operator name can be entered anyway
- Add KubernetesVersion and AppVersion
- Add a Default Maintainer when creating a new operator. It's easy to miss, and I'd rather have …

Improve UX of kudo package new

---

pkg/kudoctl/cmd/params/parser.go
pkg/kudoctl/cmd/params/parser_test.go

Reject in a human-friendly manner as below rather than panic with a stack trace.
```
$ kubectl kudo install kafka -P a.yaml 
Error: could not parse parameters: errors while unmarshaling following keys of the parameter file a.yaml: a has a null value (https://yaml.org/spec/1.2/spec.html#id2803362) which is currently not supported
$ echo $?
255
```
Fixes #1602

Reject null parameter values rather than crash.

---

keps/0032-community-repository-management.md

Detail a workflow for upstream operator developers to add or update operator packages in the community repository by referencing their upstream package.

KEP-32: Community Repository Management

---

.goreleaser.yml

https://goreleaser.com/deprecations/#brewsgithub
to test: `goreleaser check`

update for goreleaser based on deprecation

---

pkg/controller/instance/instance_controller.go

bu using the top-level `OperatorVersion` namespace instead of that of the `Instance` when resolving the dependencies.

Fix in-cluster resolver to properly resolve x-ns OV/I resources

---

pkg/kudoctl/packages/install/package.go

If skipInstance is specified, we do not need to validate the parameters - If we do, we prevent the installation of an operator version that has a parameter which is required but has no default.
Fixes #

Do not validate parameters when --skip-instance is true

---

pkg/kudoctl/cmd/testdata/invalid-params.golden
pkg/kudoctl/packages/verifier/template/verify_parameters.go
pkg/kudoctl/packages/verifier/template/verify_parameters_test.go

Parameters can be used to only trigger plans without being used in any templates. In this case no warning should be printed when verifying a package.
Fixes #1617

Don't warn if parameter is only used as trigger

---

pkg/webhook/instance_admission.go
pkg/webhook/instance_admission_test.go

Do not trigger non-existing plan

---

Makefile

`deploy-clean` is broken now.   I hesitate to remove it but it has been broken for some time which signals that it isn't used.
IF we want it than... what is recommended to add for the controller version?
Regardless... `deploy-clean` should NOT be apart of `clean` IMO. 

deploy-clean should not be part of clean

---

pkg/apis/kudo/v1beta1/instance_types.go
pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_test.go
pkg/engine/health/health.go
pkg/engine/task/task_delete.go

This fixes a bug when a sequence of apply-delete-apply meant that the resource did not exist in the end because we did not wait for item to be deleted out of the cache of the client we're using. Details are in #1596
The solution introduces "health check" for deletion which queries client until it's deleted. Instead of poll & wait and blocking the worker thread we're relying on reconciliation loop being re-trigerred. We now reschedule reconciliation when plan is running to prevent stalling. A simple backoff mechanism implemented as well.
Fixes #1596

Wait for resource being deleted, retry reconciliation

---

pkg/kudoctl/cmd/testdata/repo-list.golden
pkg/kudoctl/cmd/testdata/skip-check-add-list.golden
pkg/kudoctl/util/repo/repo.go
pkg/kudoctl/util/repo/testdata/repositories.yaml.golden

This changes the URL of the community repository to the repository managed by the [kudobuilder/operators-index](https://github.com/kudobuilder/operators-index) project.
Don't merge before https://github.com/kudobuilder/operators-index/pull/9 is merged.

Update the default community repository URL

---

pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
pkg/kudoctl/kudoinit/manager/manager.go
pkg/kudoctl/kudoinit/setup/wait.go
pkg/kudoctl/kudoinit/types.go

This is part of the solution for #1625
I ended up using startup probe instead of readiness because that's run only when manager starts, we don't need to poll the endpoint when manager is running.

Introduce readiness check and proper wait in `init --wait`

---

pkg/kudoctl/packages/verifier/template/verify_parameters.go
pkg/kudoctl/packages/verifier/template/verify_parameters_test.go

The allowlist in verifier got out of sync with reality and `package create` rejects an otherwise valid package.
Fixes #

Add a missing implicit.

---

pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/init_test.go
pkg/kudoctl/cmd/output/output.go
pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/plan/plan_history.go
pkg/kudoctl/cmd/plan/plan_status.go
pkg/kudoctl/cmd/plan/plan_status_test.go
pkg/kudoctl/cmd/plan/testdata/planstatus.json.golden
pkg/kudoctl/cmd/plan/testdata/planstatus.txt.golden
pkg/kudoctl/cmd/plan/testdata/planstatus.yaml.golden
pkg/kudoctl/cmd/testdata/deploy-kudo.json.golden
pkg/kudoctl/kudoinit/setup/setup.go

Add `--output` parameter to `kudo plan status` to allow json/yaml output instead of human readable format
Fixes #

Add --output parameter to plan status to allow json/yaml output

---

Makefile

Stumbled across an example of this and loved it.  Adds help to `make` which required rearrangement to achieved desired output.  Here is an example:
```shell
❯ make help
Usage: make <OPTIONS> ... <TARGETS>
Available targets are:
Usage:
make <target>
help             Show this help screen
Tests
test             Runs unit tests
integration-test Runs integration tests
test-clean       cleans test outputs
Development
all              Build manager and runs unit tests
lint             Run golangci-lint
manager          Builds manager
manager-fast     Builds manager without code generation
run              Runs Manager locally (requires ngrok or webhook management)
cli              Builds CLI with code generation
cli-install      Installs kubectl-kudo …
```

Makefile Help

---

.golangci.yml
pkg/controller/instance/instance_controller.go
pkg/engine/workflow/engine_test.go
pkg/kudoctl/cmd/init.go
pkg/kudoctl/cmd/plan/plan_status.go
pkg/kudoctl/cmd/plan/plan_status_test.go
pkg/kudoctl/cmd/prompt/operator.go
pkg/kudoctl/cmd/uninstall.go
pkg/kudoctl/kudoinit/crd/crds.go
pkg/kudoctl/kudoinit/manager/manager.go

stylecheck added to linting and issues resolved

---

pkg/kudoctl/kudoinit/setup/setup.go

There is a log in the `kudo init --upgrade` path that logs directly into out. This interferes with the uninstall:
`kudo init --upgrade --dry-run --output yaml | kubectl delete -f -`

Fix log for init --upgrade, interfers with --dry-run --output yaml

---

pkg/kudoctl/kudoinit/prereq/namespace.go
pkg/kudoctl/kudoinit/prereq/namespace_test.go

Check if the target namespace is terminating and abort installation

---

.circleci/config.yml
Makefile
hack/run-integration-tests.sh
hack/run-kuttl-tests.sh
test/Dockerfile

Use separate targets in Makefile so running a single suite is easier
- Separate Go integration tests and kuttl integration tests
- Test for Goland variable in running go integration tests
- Add more documentation to make help

Separate execution of Go integration tests and kuttl integration tests

---

pkg/kudoctl/cmd/package_create.go
pkg/kudoctl/cmd/package_verify.go
pkg/kudoctl/cmd/package_verify_test.go
pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/testdata/invalid-params.json.golden
pkg/kudoctl/cmd/testdata/invalid-params.txt.golden
pkg/kudoctl/cmd/testdata/invalid-params.yaml.golden
pkg/kudoctl/cmd/verify/verify.go
pkg/kudoctl/verifier/result.go

Add `--output` parameter to `package verify` and `package create`
This allows users to easily parse the output of both commands
Fixes #1644

Add "--output yaml" to kudo package verify

---

pkg/kudoctl/cmd/package_verify.go
pkg/kudoctl/cmd/plan.go
pkg/kudoctl/cmd/update.go

Was working on kudo documentation and stumbled over some inconsistencies in the command descriptions/help texts...

Small fixes in command descriptions

---

pkg/engine/task/task_apply.go

which includes the GVK of the object in question to speed up the debugging when applying fails.

Better logging for the apply task

---

pkg/engine/health/health.go
pkg/kudoctl/cmd/init.go
pkg/kudoctl/kudoinit/crd/crds.go
pkg/kudoctl/kudoinit/prereq/namespace.go
pkg/kudoctl/kudoinit/setup/setup.go
pkg/kudoctl/kudoinit/setup/wait.go

Instead of monitoring the statefulset of the KUDO manager, we can use the installers `VerifyInstallation` to wait for all resources to be healthy.
Fixes #1653

Use Verify Installation for `--wait` on init

---

pkg/kudoctl/clog/log.go
pkg/kudoctl/cmd/get.go
pkg/kudoctl/cmd/get/get.go

Update to provide proper help messaging for the get command at the root level and at the get level
```
go run cmd/kubectl-kudo/main.go -h
KUDO CLI and future sub-commands can be used to manipulate, inspect and troubleshoot KUDO-specific CRDs
and serves as an API aggregation layer.
Usage:
kubectl-kudo [command]
Examples:
...
kubectl kudo get instances [flags]
Available Commands:
diagnostics collect diagnostics
get         Gets list of installed components (instances, operators, operatorversions or all).
Flags:
-h, --help                  help for kubectl-kudo
--home string           Location of your KUDO config. (default "/Users/kensipe/.kudo")
...
Use "kubectl-kudo [command] --help" for more information about a command.
```
and 
```
go run …
```

kudo get cmd help

---

pkg/engine/health/health.go

The v1 CRD API is available since Kubernetes 1.16 and should be supported in addition to the v1beta1 API that's deprecated beginning with Kubernetes 1.19.

Return health status for V1 CRDs

---

pkg/kudoctl/cmd/get/get_test.go

Fix imports that were missed

---

pkg/kudoctl/cmd/diagnostics/print_test.go
pkg/version/version.go

This PR shows the used Kubernetes API in the version output. Helps users to understand which version of kubernetes is supported, see #1642

Add the used Kubernetes Version to `kudo version` output

---

pkg/kudoctl/cmd/uninstall.go
pkg/kudoctl/cmd/uninstall_test.go
pkg/kudoctl/util/kudo/kudo.go

Similar to the 'wait' and 'wait-time' options for operator package installations, instance uninstalls can be waited upon to complete.
Fixes #1665

Add an option to wait for an instance uninstall

---

go.sum

Go.Sum was dirty with older references... we should create a CI check for this...

Go Mod Tidy

---

Makefile
hack/install-golangcilint.sh

The new release has a `version --short` subcommand that makes it possible to
get rid of the somewhat hacky parsing.

Bump golangci-lint to, use the new version subcommand.

---

go.mod
go.sum
pkg/controller/instance/resolver_incluster.go
pkg/kudoctl/cmd/get/get.go
pkg/kudoctl/cmd/install.go
pkg/kudoctl/cmd/install/install.go
pkg/kudoctl/cmd/install/install_test.go
pkg/kudoctl/packages/convert/resources.go
pkg/kudoctl/packages/resolver/resolver.go
pkg/kudoctl/packages/resolver/resolver_incluster.go
pkg/kudoctl/packages/resolver/resolver_incluster_test.go
pkg/kudoctl/util/kudo/kudo.go
pkg/kudoctl/util/kudo/kudo_test.go
pkg/kudoctl/util/repo/resolver_repo.go

Summary:
The current `kudo install ...` command accepts either a remote repo operator name, a URL, or a local folder/tgz. This PR allows the user to install an instance from an existing in-cluster operator version using the newly introduced `--in-cluster` option:
```
❯ ./bin/kubectl-kudo install first-operator --operator-version=0.2.0 --in-cluster
operatorversion default/first-operator-0.2.0 already installed
instance default/first-operator-instance created
```
This way `kudoctl` will only look for already installed operator versions (one can list them using `kudoctl get operatorversions`) and does not need access to the repo/package files.
Fixes #1678

Install operator instance from in-cluster operator version resource

---

Makefile
hack/install-golangcilint.sh

To avoid specifying the version of `golangci-lint` in multiple places, it is now a parameter in the `install-golangcilint.sh` script. With this change, the version of `golangci-lint` is only declared in the Makefile.

Use a version parameter in the linter install script

---

.circleci/config.yml
hack/verify-go-clean.sh

Checks to see that go.mod and go.sum are clean on PRs via CI

Add go mod tidy clean verifier to CI

---

keps/0034-instance-health.md
keps/README.md

First iteration of the KEP for health.

KEP 34: Instance health

---

test/e2e/kind-config.yaml
test/kudo-e2e-test.yaml.tmpl

Use --v 4 on kube-controller-manager for debugging

---

keps/0034-instance-health.md

This PR proposes an implementation for KEP-34.

Proposal for instance readiness KEP

---

keps/0019-package-api-versioning.md

Clarify that appVersion is SemVer

Clarify SemVer usage for app version in KEP-19

---

keps/0034-instance-health.md

Move the KEP to implementable, specify some more left-overs from review.
Please take time to review also the KEP as a whole as this moves it to implementable.

Move kep to implementable, specify opt-in and out

---

pkg/kubernetes/status/health.go
pkg/kubernetes/status/health_test.go

A service is considered healthy if its cluster IP is accessible. Furthermore, if the service is load-balanced, then balancer needs to have an ingress defined.
Fixes #1699

Calculate health for services

---

pkg/kudoctl/kube/config.go

As this function is used by more functions to create Kubernetes clients, more KUDO subcommands will benefit from reduced CRD deprecation warnings when running on Kubernetes >=1.19.
Before:
```bash
$ kubectl kudo get instances
W1015 13:21:29.812992    1507 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1015 13:21:29.816993    1507 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1015 13:21:29.820192    1507 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, …
```

Move warning options to 'GetKubeClientForConfig'

---

pkg/kudoctl/packages/verifier/task/verify_build.go

Summary:
in many cases, the task's `OperatorVersion` is being set by the dependency resolver during the package installation, so that it is valid for the field to be empty during verification.

Fixing false warnings for the `KudoOperatorTask`

---

pkg/kudoctl/resources/install/operator.go

Summary:
This is necessary due to a recent [change](https://github.com/kudobuilder/kudo/commit/5e7546bf11f07924d7b1889bdebc8ed0b440ca0b) in OV naming rules: KUDO now uses the `appVersion` in the OV name if it exists and so we need to set it when `KudoOperatorTaskSpec` package is resolved.

Proper handling of the `appVersion` when resolving dependencies

---

pkg/kudoctl/util/kudo/kudo.go

CRD validation can result in warning logs on Kubernetes >=1.19. These should be skipped if running commands with '--validate-install=false'.
Before:
```
$ kubectl kudo --validate-install=false get instances
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
List of current installed instances in namespace "default":
.
```
After:
```
$ kubectl kudo --validate-install=false get instances
List of current installed instances in namespace "default":
.
```

Don't run the CRD validation if validation flag is false

---

hack/run-operator-tests.sh

Temporarily, a different brach was used in the script for KUDO 0.17 compatibility. As these changes have been merged, the default branch can be used again.

Use main branch of operators repository

---

.golangci.yml
Makefile
pkg/engine/renderer/enhancer_test.go
pkg/kudoctl/cmd/plan/plan_status_test.go
pkg/kudoctl/packages/verifier/template/verify_render_test.go

* Updated golangci-lint to version 1.32.2
* Reorganized linters to be alphabetical (making it easy to discover which are included or not)
* ignoring `gosec` for tests
Fixes #

lint bump 1.32.2

---

pkg/kudoctl/cmd/init_integration_test.go

This removes `testutils.WaitForCRDs` in favor of `envtest.WaitForCRDs` as this function will be removed from kuttl in a future release.
See: https://github.com/kudobuilder/kuttl/pull/250

Use 'envtest.WaitForCRDs'

---

pkg/webhook/instance_admission.go
test/upgrade/cert-manager-detection/06-install-kudo.yaml

It appears no one tested creating a new instance with this release of kudo.  I don't see how it could have worked.
This was tested working on konvoy 1.6-rc4 with `kudobuilder/controller:dev` which was dev build with the solution.
We will look at making sure we have a test solution after we get this bug fix out.
Fixes #1742

Fixes nil map bug on creation

---

.circleci/config.yml
Makefile
hack/run-integration-tests.sh

We agreed on this with Andreas here https://kubernetes.slack.com/archives/CG3HTFCMV/p1603361976115700?thread_ts=1603360951.111500&cid=CG3HTFCMV
Context: There was a PR that has splitted KUTTL tests out of integration-test command. The reason was to be easily able to run just a single test. But as a result, command that's named `integration-test` now runs only a subset of integration tests and I think that's very confusing. The solution is to keep kuttl test separate for whoever needs it but have all integration tests again under one makefile command.

Integration test command should run all integration tests

---

test/e2e/immutable-parameter-with-default/00-assert.yaml
test/e2e/immutable-parameter-with-default/00-install.yaml
test/e2e/immutable-parameter-with-default/immutable-param/operator.yaml
test/e2e/immutable-parameter-with-default/immutable-param/params.yaml
test/e2e/immutable-parameter-with-default/immutable-param/templates/deployment.yaml

Cassandra 1.0.2 marked a parameter as immutable, that also has a default value. That caused a regression being fixed in #1738
This is a test covering that regression. We already have a test for immutable params but they are providing a param value on install and that means the bug does not get triggered.

Add test for cassandra parameter regression

---

pkg/apis/kudo/v1beta1/instance_types.go
pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_test.go
test/e2e/upgrade/00-assert.yaml
test/e2e/upgrade/00-install.yaml
test/e2e/upgrade/01-assert.yaml
test/e2e/upgrade/01-upgrade.yaml
test/e2e/upgrade/first-operator-v2/operator.yaml
test/e2e/upgrade/first-operator-v2/params.yaml
test/e2e/upgrade/first-operator-v2/templates/configmap.yaml
test/e2e/upgrade/first-operator-v2/templates/deployment.yaml
test/e2e/upgrade/first-operator/operator.yaml
test/e2e/upgrade/first-operator/params.yaml
test/e2e/upgrade/first-operator/templates/deployment.yaml

Initialise plan status correctly if an upgraded plan adds new phases or steps
Fixes #1754

Initialise plan status correctly if an upgraded plan adds new phases or steps

---

pkg/apis/kudo/v1beta1/instance_types.go
pkg/controller/instance/instance_controller.go
pkg/controller/instance/instance_controller_test.go
test/e2e/upgrade/first-operator-v2/operator.yaml

Fix added steps in upgraded operator

---

pkg/kudoctl/kudoinit/prereq/webhook.go

Don't throw exception when running kudo init --verify against a cluster without KUDO
Fixes #1753

Fix kudo init --verify on cluster without KUDO

---

test/e2e/apply-delete-apply/00-install.yaml
test/e2e/cli-install-uninstall/00-install.yaml
test/e2e/cli-install-uninstall/01-uninstall.yaml
test/e2e/dependencies-hash/00-install.yaml
test/e2e/dependencies-hash/01-update-replicas.yaml
test/e2e/dependencies-hash/02-update-param.yaml
test/e2e/dependencies-hash/03-update-replicas-again.yaml
test/e2e/immutable-parameter-with-default/00-install.yaml
test/e2e/immutable-parameter/00-install.yaml
test/e2e/readiness/00-install.yaml
test/e2e/toggle-task/01-update.yaml
test/integration/first-operator-test/00-install.yaml
test/integration/update-command/02-update.yaml
test/integration/upgrade-command/00-install.yaml
test/integration/upgrade-command/01-upgrade.yaml
test/kudo-e2e-test.yaml.tmpl
test/kudo-integration-test.yaml
test/kudo-upgrade-test.yaml.tmpl
test/upgrade/cert-manager-detection/02-remove-kudo.yaml
test/upgrade/cert-manager-detection/03-uninstall-cert-manager-0-16-0.yaml
test/upgrade/cert-manager-detection/05-install-cert-manager-1-0-3.yaml
test/upgrade/cert-manager-detection/06-install-kudo.yaml
test/upgrade/cert-manager-detection/99-remove-kudo.yaml
test/upgrade/upgrade-to-current/00-install-old-kudo.yaml
test/upgrade/upgrade-to-current/01-install-operator.yaml
test/upgrade/upgrade-to-current/02-upgrade-kudo.yaml
test/upgrade/upgrade-to-current/03-upgrade-operator.yaml
test/upgrade/upgrade-to-current/99-remove-kudo.yaml

Kudo.dev for these resources have been deprecated for a while.

Update apiversion from kudo to kuttl

---

Makefile
pkg/kudoctl/packages/verifier/template/verify_references.go
pkg/kudoctl/packages/verifier/template/verify_render.go
test/integration/dependencies-package-create/00-install.yaml
test/integration/dependencies-package-create/operator-with-dependencies/child-operator/operator.yaml
test/integration/dependencies-package-create/operator-with-dependencies/child-operator/params.yaml
test/integration/dependencies-package-create/operator-with-dependencies/parent-operator/operator.yaml
test/integration/dependencies-package-create/operator-with-dependencies/parent-operator/params.yaml
test/integration/dependencies-package-create/operator-with-dependencies/parent-operator/templates/child-params.yaml

Child params in operators with dependencies failing in pkg resolver

---

pkg/webhook/instance_admission.go
test/e2e/update-with-upgrade/00-assert.yaml
test/e2e/update-with-upgrade/00-install.yaml
test/e2e/update-with-upgrade/01-assert.yaml
test/e2e/update-with-upgrade/01-upgrade-operator-version.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v1/operator.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v1/params.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v1/templates/configmap-deployed.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v1/templates/configmap-updated.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v1/templates/configmap-upgraded.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v2/operator.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v2/params.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v2/templates/configmap-deployed.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v2/templates/configmap-updated.yaml
test/e2e/update-with-upgrade/update-with-upgrade-v2/templates/configmap-upgraded.yaml

Now, parameters added by a new operator version (for example, when
a new OV brings in a new required parameter with no default, so that
it is necessary to set a value together with upgrade) no longer trigger
an update plan.
Fixes #1776

Do not trigger an update when a parameter is added by an OV upgrade. 

---

test/e2e/dependencies-hash/05-update-param-and-replica.yaml
test/e2e/immutable-parameter/01-fail-to-update-param.yaml
test/e2e/plan-trigger/00-install.yaml
test/e2e/plan-trigger/01-trigger.yaml
test/e2e/terminal-failed-job/00-install.yaml
test/e2e/terminal-failed-job/01-install-timeout.yaml
test/e2e/toggle-task/00-install.yaml
test/e2e/toggle-task/02-update.yaml
test/e2e/upgrade/00-install.yaml
test/e2e/upgrade/01-upgrade.yaml
test/integration/cli-install/00-install.yaml
test/integration/install-existing-crds-in-operator/00-install-operator.yaml
test/integration/invalid-crd-install/00-install.yaml
test/integration/operator-with-custom-crd/00-install-crd.yaml
test/integration/operator-with-dependencies/01-install.yaml
test/integration/operator-with-subdirectory-resources/00-install.yaml
test/integration/parameter-types-operator/01-install.yaml
test/integration/remove-pod-container/00-install.yaml
test/integration/remove-pod-container/01-update.yaml
test/integration/remove-pod-container/02-update_param.yaml
test/integration/upgrade-with-dependencies/00-install.yaml
test/integration/upgrade-with-dependencies/01-upgrade.yaml
test/upgrade/cert-manager-detection/00-install-cert-manager-0-16-0.yaml
test/upgrade/cert-manager-detection/01-install-kudo.yaml

Signed-off-by: Rishabh Bohra <rishabhbohra01@gmail.com>
Updates the `apiVersion` to `kuttl.dev/v1beta1` for the tests that were missed in the PR https://github.com/kudobuilder/kudo/pull/1762

Update leftover apiVersion from kudo to kuttl

---

.github/CODEOWNERS
OWNERS

Hi all,
It has been a pleasure working with the KUDO community. I've enjoyed building it from proposal, to first commit, and working to make developing controllers on Kubernetes more accessible for everyone. This PR is me passing the torch off to others who are contributing today. Other things are consuming most of my time and the ownership of this project should be in the hands of everyone who's working hard to make KUDO better!
Thanks all!
Signed-off-by: Gerred Dillon <hello@gerred.org>

Remove Gerred from ownership
