pkg/controller/instance/instance_controller.go, pkg/controller/planexecution/planexecution_controller.go, pkg/util/health/ready.go
=> Changed all fmt.Printf and fmt.Println to log.Printf and log.Println

README.md
Inline code highliting for "Get maestro repo" command.
=> Inline code highliting for "Get maestro repo" command

README.md
Updated `README.md` and added pre-requisites to fix #75
=> README: added pre-requisites

README.md
Fixed broken Documentation link
=> fixed broken docs link

docs/Backups.md
Fixed some concerns addressed here https://github.com/kudobuilder/kudo/pull/79 and added the demo video from our `SIG-APPS` presentation.
=> Added MySQL demo video and fixed typos

keps/0001-kep-process.md
/kind kep
Status of this kep wasn't changed accordingly as well as its number:
- Changed the status from `provisional` to `implemented`
- Changed the kep number from `draft-20190219` to `1`
Fixes #
```release-note
```
=> [KEP 0001] Changed status to implemented

keps/0002-dynamic-crds.md
This KEP is for dynamic CRDs. In the spirit of the KEP process, we should merge this as minimally as possible and continue adding PRs to flesh it out.
=> [KEP 0002] Initial work on Dynamic CRDs

keps/0006-stable-kafka-example.md, keps/draft-20190307-stable-kafka-example.md
/kind kep
This KEP proposes to create a stable example for a Kafka framework and its dependency Zookeeper, along with defining criteria for what is considered stable.
=> [KEP draft-20190307] Stable Kafka Example

site/content/_index.md
>
> /kind bug
> /kind design
> /kind kep
Fixes #
```release-note
```
=> Added links to the main GH repo.

keps/0006-stable-kafka-example.md
There's no base proposal here defining production ready so we're not yet implementable on this. Changing to provisional and adding a proposal section so we can flesh that out.
=> Change to provisional status

README.md
Updates the README to add info on community meetings
Fixes #151
=> Add community meetings to README

keps/0006-stable-kafka-example.md
/kind kep
Adds user stories to KEP 0006
I'd like feedback on the general format of the user stories. Are they helpful that way? Too generic or too specific? They try to capture the problem a user wants to solve, without getting into a specific solution.
Do these stories capture everything we expect from a stable Kafka built on KUDO?
no
```release-note
NONE
```
=> [KEP 0006] Stable Kafka Example - Add user stories

README.md
Updating the quick start video by showcasing Zookeeper/Kafka installation with KUDO
Fixes https://github.com/kudobuilder/kudo/issues/108
```release-note
NONE
```
=> Update of Quickstart Video

Gopkg.lock, pkg/controller/planexecution/planexecution_controller.go
/kind bug
Fixes scaling of Deployments due to wrong type assertion.
Fixes https://github.com/kudobuilder/kudo/issues/155
Looking at https://github.com/kudobuilder/kudo/pull/100 I don't think it is https://github.com/kudobuilder/kudo/issues/58 but separate.
```release-note
```
=> Fixing scaling of Deployments

keps/0006-stable-kafka-example.md
=> @ryadav88 feedback on Kafka stories

README.md
Provides notes to builds detailing what is expected which otherwise can be surprising to the users first build.
Fixes #
```release-note
NONE
```
=> Enhancing the details around first build

docs/cli.md, site/config.yml
=> Polish CLI instructions

.gitignore, cover.out
/kind cleanup
Reduce `git` overhead and chores.  Enable more collaborative environment.   
No checkin of generated output i.e., `cover.out`.
Fixes #
```release-note
NONE
```
=> updating the ignore

README.md, docs/getting-started.md
Fixes #
```release-note
NONE
```
=> Update README to include run requirements and how to run the CLI

Makefile
/kind cleanup
* Adding cleanup tasks
* Adding distribution builds
Fixes #
This update expects #185 to land.  There is an expectation that the `/bin` directory is NOT checked in.
```release-note
NONE
```
=> Makefile clean and Builds Distributions

docs/getting-started.md
Just a tiny link fix in the getting-started.md docs I noticed when I read through it.
`nil`
=> Fix kafka example link in getting-started.md

docs/Comparison.md, site/themes/book/assets/_variables.scss
/kind cleanup
The tools comparison table did not look good on the website.  https://kudo.dev/docs/comparison/#comparison-table
1. Fixed table to render as a table.
2. Aligned cells for best look
3. emboldened tools / projects 
Fixes #
```release-note
NONE
```
=> Comparison table was not created correctly.   Cleaned up table.

CONTRIBUTING.md
Thanks https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md for the language. Might be some other things there that would be helpful to incorporate.
=> Update CONTRIBUTING.md to be more friendly

.github/CODEOWNERS
/kind cleanup
Ken needs some props
```release-note
None
```
=> Added Ken to CodeOwners

docs/cli.md
Fixes a typo in docs/cli.md.
```release-note
NONE
```
=> Fix typo in docs/cli.md, kubebuilder -> kudobuilder.

docs/getting-started.md
Apparently hugo does not like asterisked bullet points leading to broken formatting.
```release-note
NONE
```
=> Fix markup

keps/0008-framework-testing.md, keps/draft-20190503-framework-testing.md
/kind kep
This introduces a proposal for declaratively authoring and running acceptance and unit tests for KUDO frameworks.
=> DCOS-53410 - KEP for acceptance testing KUDO Frameworks

keps/0008-framework-testing.md
=> Update KEP-0008 status to implementable.

docs/update-upgrade-plans.md
Typo fix.
```release-note
NONE
```
=> Use the intended word

keps/0004-add-testing-infrastructure.md
/kind kep
The long sentence is hard to follow. Adding "that" makes it clearer.
```release-note
NONE
```
=> Clarification

keps/0008-framework-testing.md
/kind kep
Typos and markup fixes.
```release-note
NONE
```
=> Fix markup and some typos

docs/getting-started.md
>
> /kind bug
> /kind design
> /kind kep
Update docs to show installing CRDs using kubectl instead of the Makefile provided function
Fixes
This was suggested in #209, and simplifies understanding of what is being installed without the user having to dig into the Makefile
```release-note
NONE
```
=> Add using kubectl to install the CRDs

keps/20190514-operator-toolkit.md
/kind kep
Fixes #
```release-note
NONE
```
=> Adding KEP for operator toolkit

Makefile
/kind bug
The make file had a missing space between " and -0 resulting in a failure to build the windows artifacts.
Fixes #
```release-note
NONE
```
=> fixing bug in building windows artifacts with make

docs/community.md, docs/examples/_index.md, site/themes/book/layouts/partials/docs/shared.html
Add links to community content and frameworks repo.
=> Add links to community content and frameworks repo.

pkg/kudoctl/cmd/install/install_test.go, pkg/kudoctl/util/check/check.go
/kind bug
Fixes test of InstallCmd to allow for passing CI builds
none
The check didn't handle folders correctly.
```release-note
None
```
=> Install cmd test fix

.circleci/config.yml
This ensures that new features also pass testing when merged with master.
Do we still want to run the test suite on the local branch, or is that redundant?  It might help developers determine if the issue is with their branch, or how their branch merges with master, but will cause an increase in test times
```release-note
None
```
=> Also run tests against the merge of master into the current branch

.dockerignore, test/.dockerignore
/kind cleanup
git repos and parts of `hack` were being passed to docker builds.
Running tests now only requires a small docker context to be passed
```bash
$ ./test/run_tests.sh
Sending build context to Docker daemon  667.6kB
```
```release-note
None
```
=> Added additional folders to .dockerignore.  Moved to top level

keps/0009-operator-toolkit.md
/kind cleanup
Minor improvements KEP-0009, in particular I:
* Fixed typos
* Fixed links
* Removed empty sections
* Tried to make wording a bit clearer
```release-note
NONE
```
=> Improve KEP-0009

pkg/controller/framework/framework_controller.go, pkg/controller/frameworkversion/frameworkversion_controller.go, pkg/controller/instance/instance_controller.go, pkg/controller/planexecution/planexecution_controller.go
/kind cleanup
```release-note
NONE
```
=> Correct spelling of 'Received' in log output

Makefile
/kind cleanup
Fixes #
```release-note
NONE
```
=> convince->convenience

.circleci/config.yml
>
/kind cleanup
I believe we don't need two tasks for checking formatting. Only one that does it after master was merged into this branch should be enough.
```release-note
NONE
```
=> Just one formatting job

docs/cli.md
Minor improvements to the CLI docs.
Fixes #226.
```release-note
NONE
```
=> CLI docs improvements

go.sum, pkg/kudoctl/cmd/get.go, pkg/kudoctl/cmd/install.go, pkg/kudoctl/cmd/install_test.go, pkg/kudoctl/cmd/plan.go, pkg/kudoctl/cmd/root.go, pkg/kudoctl/cmd/version.go
/kind cleanup
Fixes #307 
```release-note
NONE
```
=> making commands private

docs/repository.md, pkg/kudoctl/cmd/install/install.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Making code easier to read

pkg/kudoctl/cmd/install/install.go
/kind bug
Fixes #
```release-note
NONE
```
=> reverted code refactor which broken install test

docs/examples/apache-kafka.md
>
> /kind bug
> /kind design
> /kind kep
Fixes #
```release-note
```
=> link to zookeeper is broken

pkg/apis/kudo/v1alpha1/frameworkversion_types.go, pkg/apis/kudo/v1alpha1/frameworkversion_types_test.go, pkg/apis/kudo/v1alpha1/instance_types.go, pkg/apis/kudo/v1alpha1/planexecution_types.go, pkg/controller/frameworkversion/frameworkversion_controller.go, pkg/controller/instance/instance_controller.go, pkg/controller/planexecution/planexecution_controller.go, pkg/kudoctl/cmd/install/install.go, pkg/kudoctl/cmd/plan/plan_history.go, pkg/kudoctl/util/kudo/kudo.go, pkg/kudoctl/util/repo/repo.go, pkg/util/health/ready.go
Minor code style cleanups to improve readability.
```release-note
NONE
```
=> Clean up comments

.github/CODEOWNERS
Updating code owners:
Adding alenkacz to CLI
Adding jbarrick-mesosphere to testing
Adding gerred to website
Fixes #
```release-note
NONE
```
=> updating codeowners

pkg/kudoctl/util/repo/package_test.go, pkg/kudoctl/util/repo/testdata/zk-crd-golden/zookeeper-framework.yaml, pkg/kudoctl/util/repo/testdata/zk/framework.yaml
>
> /kind bug
> /kind design
> /kind kep
Fixes #
```release-note
```
=> Added more fields to zk test data.  re-open tarball from aero for tests

pkg/apis/kudo/v1alpha1/frameworkversion_types.go
I seriously struggled understanding what is it saying. I had to go to code to actually understand it.
=> Better docs for Trigger field

pkg/kudoctl/cmd/install.go, pkg/kudoctl/cmd/install_test.go
refactor parameter parsing to be in a method.  focusing testing on paramater parsing and results
Fixes #
```release-note
NONE
```
=> Install Parameter Parsing Cleanup w/ Tests

pkg/controller/instance/instance_controller_suite_test.go, pkg/controller/instance/instance_controller_test.go
This adds the integration test build tag to the instance controller test suite so that they do not run on unit tests runs.
Fixes #338 
```release-note
NONE
```
=> set integration test tags on instance_controller tests.

.circleci/config.yml
/kind cleanup
We currently run the tests for both the PR and the merge target. This changes it so that we only run the tests once for the merge target to halve build times.
Fixes #424
```release-note
NONE
```
=> Run Circle CI only for the merge target.

keps/0009-operator-toolkit.md
/kind kep
Reflect the current status of this KEP and some minor naming changes :)
```release-note
NONE
```
=> Update KEP-9 to implemented

pkg/kudoctl/cmd/install/install.go, pkg/kudoctl/util/kudo/kudo.go, pkg/kudoctl/util/kudo/kudo_test.go
/kind bug
Fixes a bug when there could have been only one instance of a FV inside a namespace.
Fixes #383
```release-note
Fixed a bug that was preventing install of multiple instances of a framework into a namespace
```
=> Allow to install multiple instances of the same FV

docs/community.md
>
> /kind bug
> /kind design
> /kind kep
Fixes #
```release-note
```
=> Add slides from Warsaw Meetup.

docs/deployment/20-deployment.yaml
/kind cleanup
Release 0.3.0 to deployment.yaml
```release-note
NONE
```
=> Update KUDO version to 0.3.0 in deployment.yaml.

config/samples/kafka-instance.yaml
Somehow this was not working until I made this change.
/kind cleanup
Fixes #486
```release-note
NONE
```
=> Fix apiVersion

pkg/kudoctl/util/repo/package.go
/kind bug
```release-note
Fixes a bug where trigger from params was not propagated to the server side
```
=> Propagate trigger from CLI to the server side

pkg/kudoctl/bundle/package.go, pkg/kudoctl/bundle/testdata/zk-crd-golden1/instance.golden, pkg/kudoctl/bundle/testdata/zk-crd-golden1/operatorversion.golden, pkg/kudoctl/bundle/testdata/zk-crd-golden2/instance.golden, pkg/kudoctl/bundle/testdata/zk-crd-golden2/operatorversion.golden
/kind bug
Right now it was not able to install into specific namespace.
Fixes #344
```release-note
Fixed a bug when using `kudo install --namespace xxx` was not respected. It was not possible to install into non-default namespace
```
=> Fix install into non-default namespace

site/config.yml, site/layouts/docs/baseof.html, site/layouts/partials/head.html
/kind feature
Update the website so that the title is properly displayed based on the page being shown.
It's similar to the fix for #474 but site-wide.
```release-note
NONE
```
=> Set title tag everywhere based on page name

test/run_tests.sh
/kind bug
Fixes #365 
```release-note
NONE
```
=> Retry docker pull in tests if it fails.

keps/0012-operator-extensions.md
>
> /kind bug
> /kind design
> /kind kep
Fixes #
```release-note
```
=> Set KEP 12 to Implementable

pkg/kudoctl/util/repo/repo_index.go, pkg/kudoctl/util/repo/repo_operator.go
Minor cleanups.
```release-note
NONE
```
=> Clean up repo management functions

pkg/kudoctl/bundle/package.go
Small PR to fix the operator label in the instance. That was hardcoded to `zookeeper`
/kind bug
Fixes #558
```release-note
```
=> use correct operator label for instance in KUDO cli

RELEASE.md
/kind cleanup
Adds details to dev expectations and release branching
Fixes # 568
```release-note
NONE
```
=> adding dev and release branch details

site/data/events/cloudnativeparis.yaml, site/data/events/kubernetesedinburgh.yaml
Update community / events section to cover Edinburgh and Paris.
```release-note
NONE
```
=> Update Events for Edinburgh and Paris

pkg/controller/planexecution/planexecution_controller.go, pkg/test/test_data/patch/00-assert.yaml, pkg/test/test_data/patch/01-assert.yaml
=> Do not apply label with version to fix upgrade issues

pkg/controller/planexecution/planexecution_controller.go
=> Do not Get after Create/Patch in plan execution controller

docs/developing-operators.md
Another part of the developer docs - this time templates and params.
=> Docs for templates and params

pkg/kudoctl/util/kudo/kudo.go, pkg/kudoctl/util/kudo/kudo_test.go
I am hoping to have e2e tests with CLI soon so we can actually catch these in CI :)
=> Fix leftover bug after renaming of labels

OWNERS
/kind cleanup
Add @alenkacz, @kensipe, and myself to reviewers/approvers.
=> Update OWNERS file.

site/data/events/cloudnativecomputingswitzerland.yaml, site/data/events/cloudnativeglasgow.yaml, site/data/events/kubernetescolorado.yaml, site/data/events/kubernetesfinland.yaml
>
> /kind bug
> /kind design
> /kind kep
Update website event queue
Fixes #
```release-note
NONE
```
=> Update event queue

pkg/kudoctl/cmd/install.go, pkg/kudoctl/cmd/plan.go, pkg/kudoctl/cmd/test.go, pkg/kudoctl/cmd/version.go
/kind cleanup
We're not even using arrows consistently and don't understand why we used it in the first place as pointed out by @kensipe 
```release-note
NONE
```
=> Drop arrows from short descriptions

.gitignore
/kind cleanup
Fixes #
```release-note
NONE
```
=> Add generated kubeconfigs and kubeconfig cache to gitignore.

hack/generate_krew.sh
/kind cleanup
This updates our generate_krew.sh script to generate a manifest that confirms to the review feedback given in https://github.com/kubernetes-sigs/krew-index/pull/189
```release-note
NONE
```
=> Backport Krew review feedback to generate_krew.sh

pkg/kudoctl/cmd/install.go, pkg/kudoctl/cmd/update.go, pkg/kudoctl/cmd/upgrade.go, pkg/kudoctl/cmd/version.go
=> Remove SilenceUsage:true from all commands

pkg/kudoctl/cmd/upgrade.go
When upgrade passes, there are no messages in stdout to be able to see what it actually did. This aligns the command more with the messages we print out in install.
```release-note
NONE
```
=> Print out some messages in happy path of kudo upgrade

docs/examples/apache-kafka.md, docs/examples/apache-zookeeper.md
This PR updates the examples on how to install an operator like Zookeeper or Kafka
=> kafka: use kudo cli in the quickstart examples

site/content/posts/announcing-kudo-0.5.0.md
Adds blogpost for the latest 0.5.0 release.
```release-note
NONE
```
=> Blogpost for 0.5.0

docs/developing-operators.md
=> fix lingo in docs: task, not step

site/data/events/cloudnativehamburg.yaml
The events page currently doesn't list this event
There's no associated issue
You are all awesome
```release-note
NONE
```
=> Add Hamburg meetup

test/integration/upgrade-command/01-assert.yaml, test/integration/upgrade-command/second-operator/operator.yaml
/kind test
This tests that the upgrade command executes upgrade plan.
Fixes #403
```release-note
NONE
```
=> Upgrade plan test

docs/cli.md
Adds missing docs for upgrade and update command added in 0.5.0.
```release-note
NONE
```
=> Add update and upgrade docs

site/data/events/kubernetesandcloudnativearkansas.yaml
>
> /kind bug
> /kind design
> /kind kep
> /kind test
Fixes #
```release-note
NONE
```
=> Add Arkansas event

site/data/events/cloudnativeaarhus.yaml, site/data/events/cloudnativecopenhagen.yaml, site/data/events/cloudnativestockholm.yaml, site/data/events/sandiegocloudnativecomputingmeetup.yaml
>
> /kind bug
> /kind design
> /kind kep
> /kind test
Fixes #
```release-note
NONE
```
=> Add Nordics tour and San Diego

site/data/events/kubernetespheonix.yaml
>
> /kind bug
> /kind design
> /kind kep
> /kind test
Fixes #
```release-note
NONE
```
=> Add Phoenix date

site/data/events/cloudnativeglasgow.yaml
>
> /kind bug
> /kind design
> /kind kep
> /kind test
Fixes #
```release-note
NONE
```
=> Change date for Glasgow

site/data/events/cloudnativeaarhus.yaml, site/data/events/cloudnativecopenhagen.yaml, site/data/events/cloudnativestockholm.yaml, site/data/events/kubernetestampa.yml
Add details for the KUDO talk at the Tampa Kubernetes Meetup.
Also capitalise KUDO in other events for consistency's sake.
```release-note
NONE
```
=> Add Tampa Kubernetes Meetup information

site/data/events/datanativesvienna.yaml
Add KUDO talk details for data natives Vienna meetup
```release-note
NONE
```
=> add Data Natives Vienna meetup information

pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_instance.go, pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_operator.go, pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_operatorversion.go, pkg/client/clientset/versioned/typed/kudo/v1alpha1/instance.go, pkg/client/clientset/versioned/typed/kudo/v1alpha1/operator.go, pkg/client/clientset/versioned/typed/kudo/v1alpha1/operatorversion.go, pkg/client/informers/externalversions/kudo/v1alpha1/interface.go
/kind cleanup
A previous update to these files makes sense from a grammar stand point, however these files are generated and the grammar concern on in the tooling.   This is why I don't like checking in generated files. 
Fixes #
```release-note
NONE
```
=> Generated Files Fix

go.mod, go.sum, pkg/test/step.go, pkg/test/utils/kubernetes.go
/kind cleanup
Updated controller-runtime and controller-tools dependencies, also run `go mod tidy`
Fixes #745 
```release-note
NONE
```
=> Update controller dependencies

.goreleaser.yml
/kind cleanup
https://goreleaser.com/deprecations/#brew
Fixes #
```release-note
NONE
```
=> brew is deprecated and replaced by a brews list

README.md
/kind cleanup
```release-note
NONE
```
=> Remove broken link to getting started GIF

pkg/kudoctl/cmd/init/crds.go, pkg/kudoctl/cmd/init/prereqs.go, pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
* fix serialization bug and test to confirm correct format
* removing template tags from CRD property description
=> Backport (0.6) Bug Fix: Init YAML Generation (#813)

pkg/kudoctl/cmd/repo_index.go
/kind bug
fixing misuse of var name and error handling for no config in repo
Fixes #
```release-note
NONE
```
=> BUGFIX: repo index --url-repo 

config/samples/first-operator/operator.yaml
=> Fixes Master based on Kubernetes Version

pkg/kudoctl/util/repo/repo_operator.go
/kind feature
Lets actually use the URL listed in the index yaml :)
Replaces #837  with all comments addressed and with approvals.   The refactoring didn't allow for an easy rebase from branch PR was from... this is a cherry pick of the changes on top of master.
Fixes #
```release-note
NONE
```
=> Package URLS in index used

pkg/controller/planexecution/planexecution_controller.go
Because the case that `err != nil` is already handled above and returns, `err` will be `nil` here.
=> Remove a nil-dereference

keps/0018-controller-overhaul.md
It's targeted for 0.7.0 and we did a lot of design work on it already, I think it is implementable by now.
=> Move KEP-18 to implementable

.github/CODEOWNERS
Alternative proposal based on discussion in #845 the reasoning is that the project is small enough for everyone to be able to review everything right now so we're just tearing down walls.
I've included the current core-maintainers as owners for everything (I did not want to dishonor anyone so let me know if you feel that way). With the only exception of test where I think it still makes sense to always request review from Justin since he has the most knowledge there.
Let me know what you think :)
=> Define core owners of KUDO

pkg/kudoctl/cmd/init.go
There was a typo I saw when using init locally. When I was in there I also rephrased some of the other examples.
=> Fix typo in examples and change the wording a bit

cmd/manager/main.go
Even though this is the recommended way to register scheme, it does not go well with the dynamic nature of kudo where we don't know what types users will use in their operators. Switching back to the previous registration.
=> Fix scheme to support all apigroups

pkg/kudoctl/cmd/testdata/repo-list.golden, pkg/kudoctl/cmd/testdata/skip-check-add-list.golden, pkg/kudoctl/util/repo/repo.go, pkg/kudoctl/util/repo/testdata/repositories.yaml.golden
Reset the default community repo url 
Fixes #
=> reset to default community repo url

cmd/manager/main.go
Backport of #904 needed for 0.7.3
=> add apiextensionsv1beta1 to scheme (#904)

pkg/kudoctl/cmd/init.go, pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
CRDs were missing so everyone using 
```
kubectl kudo init --dry-run -o=yaml > kudo.yaml
kubectl apply -f kudo.yaml
```
had cluster in an incorrect state
Fixes #922
=> Include CRDs in the -o yaml --dry-run

go.mod, go.sum
go mod changes makes repo dirty.  this resolves that
Fixes #
=> Clean builds for integration tests

.github/workflows/release-on-master.yml
It fixes the Github Actions release workflow.
Fixes #908
=> Fixes the release workflow for Docker images

pkg/apis/kudo/v1alpha1/instance_types.go, pkg/apis/kudo/v1alpha1/instance_types_test.go, pkg/controller/instance/instance_controller.go, pkg/controller/instance/plan_execution_engine.go, pkg/controller/instance/plan_execution_engine_test.go, pkg/kudoctl/cmd/plan/plan_status.go
=> Plan status should show last executed plan, not just active plan

pkg/kudoctl/cmd/install/install.go, pkg/kudoctl/cmd/repo_index.go, pkg/kudoctl/util/repo/repo.go, pkg/kudoctl/util/repo/repo_operator.go
Fixes bug resulted in panic
Fixes #927
=> fixing repo merge by name bug

pkg/kudoctl/cmd/init/crds.go, pkg/kudoctl/cmd/init/manager.go, pkg/kudoctl/cmd/init/prereqs.go
Do not reimplement something that already exists as a library function.
=> Use built in isExists

pkg/kudoctl/cmd/init/crds.go, pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden, test/manifests/test-operator.yaml
This is current master
```
➜  kudo git:(av/last-executed-plan) ✗ ./bin/kubectl-kudo install zookeeper --instance zk
Error: installing single Operator: installing zookeeper-operator.yaml: installing Operator: Operator.kudo.dev "zookeeper" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"kudo.dev/v1alpha1", "kind":"Operator", "metadata":map[string]interface {}{"creationTimestamp":"2019-10-11T07:45:07Z", "generation":1, "labels":map[string]interface {}{"controller-tools.k8s.io":"1.0"}, "name":"zookeeper", "namespace":"default", "uid":"44c7bb07-1095-4dbe-883e-06254caf058f"}, "spec":map[string]interface {}{"kubernetesVersion":"1.5.1", "kudoVersion":"0.3.0", "maintainers":[]interface {}{map[string]interface …
```
=> Maintainers is array, not object

pkg/apis/kudo/v1alpha1/instance_types.go, pkg/controller/instance/instance_controller.go
The logic that was there before was probably too complicated even for me, I tried to clean it up, hopefully this removes the flake. If not, we can reopen the issue.
Fixes #947
=> Cleanup lastexecutedplan method to remove the flake

pkg/apis/kudo/v1alpha1/instance_types.go, pkg/apis/kudo/v1alpha1/instance_types_test.go
=> Backport of fixes to TestGetLastExecutedPlanStatus

pkg/kudoctl/cmd/plan/plan_history.go
Backport of https://github.com/kudobuilder/kudo/commit/99bfb3e65be1b7b5b1e4e34591c4eb31c529dd2d with just small merge conflict resolution
=> Backport of plan history fix on unknown instance

hack/generate_krew.sh
=> Make it possible to run krew even from macos

pkg/kudoctl/cmd/init/crds.go, pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden, pkg/test/utils/dynamicrestmapper.go, pkg/test/utils/kubernetes.go
This is really just a small cleanup + removed dependencies from OV and I (I stumbled upon that on Friday).
=> Small cleanup of init

cmd/manager/main.go, pkg/apis/kudo/v1alpha1/register.go
sigs.k8s.io/controller-runtime/pkg/runtime/log is deprecated in favor of sigs.k8s.io/controller-runtime/pkg/log,
sigs.k8s.io/controller-runtime/pkg/runtime/scheme is deprecated in favor of sigs.k8s.io/controller-runtime/pkg/scheme.
=> Chore: Remove usage of deprecated packages

go.mod, go.sum
'controller-tools' v0.2.2 has updated dependencies on Kubernetes 1.16.
=> chore: Update 'controller-tools'

hack/run-e2e-tests.sh
We no longer use dev because everything is merged to master.
=> Switch e2e to master

go.mod, go.sum, pkg/kudoctl/cmd/operator_verify.go, pkg/kudoctl/cmd/operator_verify_test.go, pkg/kudoctl/cmd/testdata/invalid-params.golden, pkg/kudoctl/cmd/testdata/invalidzk/operator.yaml, pkg/kudoctl/cmd/testdata/invalidzk/params.yaml, pkg/kudoctl/cmd/testdata/invalidzk/templates/pdb.yaml, pkg/kudoctl/cmd/testdata/invalidzk/templates/services.yaml, pkg/kudoctl/cmd/testdata/invalidzk/templates/statefulset.yaml, pkg/kudoctl/cmd/testdata/invalidzk/templates/validation.yaml, pkg/kudoctl/cmd/verify/verify.go, pkg/kudoctl/cmd/verify/verify_test.go, pkg/kudoctl/packages/package_manager.go
Adds `operator verify` which currently checks params around chars and dups
Fixes #
=> adding verification to operators around params

pkg/test/test_data/create-or-update/00-assert.yaml, pkg/test/test_data/create-or-update/00-crd.yaml
This will prevent the builds from failing :)
=> Prow CRD now has no schema in tests

CONTRIBUTING.md
=> Fix markup and a link.

pkg/kudoctl/util/kudo/kudo.go
This resolves issues with hanging deletions due to foreground deletion finalizers not being able to run in certain scenarios.
Fixes #1071
=> Change delete propagation to background

pkg/kudoctl/cmd/package_create.go, pkg/kudoctl/cmd/package_test.go, pkg/kudoctl/cmd/package_verify.go
=> connecting package verification to package creation

pkg/apis/kudo/v1beta1/instance_types.go, pkg/controller/instance/instance_controller.go, pkg/kudoctl/cmd/init.go, pkg/test/utils/kubernetes.go
=> chore: Fix a few typos

pkg/kudoctl/cmd/package_params_list.go
=> Fix kubectl-kudo flag conflict #1120

cmd/manager/main.go, go.mod
One less logging library - yay! Also the logging around webhooks was broken.
Thanks @nfnt
=> Remove logr and use log for now in manager.main

.golangci.yml, Makefile
`golangci-lint` bundles `goimports`. By using this linter instead, the `.golangci.yml` configuration is used, which skips linting for directories that contain autogenerated code.
=> Use 'goimports' provided by 'golangci-lint'

pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden, pkg/kudoctl/kudoinit/prereq/webhook.go, pkg/kudoctl/kudoinit/setup/setup.go
The bug was in the for loop :-)
=> Revert logging changes and fix a bug

pkg/apis/kudo/v1beta1/operatorversion_types.go, pkg/apis/kudo/v1beta1/test_types.go
Example messages:
```
pkg/apis/kudo/v1beta1/test_types.go:93:2: encountered struct field "Labels" without JSON tag in type "ObjectReference"
Error: not all generators ran successfully
```
This does not seem to have any effect otherwise.
This is another baby step towards #862
=> Use empty json tags to please controller-gen.

config/crds/kudo_v1beta1_instance.yaml, pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden, pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden, pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden, pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden, pkg/kudoctl/kudoinit/crd/crds.go
It seems to me that this had been a typo.
This is a baby step towards #862.
=> Start operatorVersion field with lower-case letter.

.github/PULL_REQUEST_TEMPLATE.md
Contributor cannot add labels. Also rephrased the sentence about tests.
Fixes #1049
=> Adjust description in the PR template

.pre-commit-config.yaml, hack/install-golangcilint.sh
Use the latest release of `golangci-lint`
=> Bump 'golangci-lint' to v1.22.2

hack/run-e2e-tests.sh
Without this running e2e tests fails on my workstation.
Fixes #1258
=> Include dots in regex for image version substitution.

pkg/kudoctl/cmd/upgrade.go
Looks like this was missed when changing from --version to --operator-version elsewhere.
=> Fix flag name in example.

pkg/engine/workflow/engine.go
`isFinished` and `isInProgress` is the same as [here](https://github.com/kudobuilder/kudo/blob/master/pkg/apis/kudo/v1beta1/instance_types.go#L166) and [here](https://github.com/kudobuilder/kudo/blob/master/pkg/apis/kudo/v1beta1/instance_types.go#L171). So we can reuse the code.
=> Refactored phase status checking.

keps/0023-enable-disable-features.md, keps/README.md
Signed-off-by: Zain Malik <zmalikshxil@gmail.com>
We might still add alternatives in KEP-23 but there was enough consensus to implement the current toggle task proposal. Moving the KEP to `implementable`
=> move kep-23 to implementable

.github/release-drafter.yml
- Add Template for Release Drafter (https://github.com/release-drafter/release-drafter)
=> Add release-drafter template

pkg/engine/renderer/engine.go, pkg/engine/renderer/engine_test.go, pkg/engine/renderer/functions.go
This implements [KEP-25](https://github.com/kudobuilder/kudo/blob/master/keps/0025-template-to-yaml-function.md).
=> KEP-25: Implementation of toYaml function.

keps/0025-template-to-yaml-function.md, keps/README.md
=> Mark KEP-25 as implemented and refresh list.

.github/release-drafter.yml, CONTRIBUTING.md, RELEASE.md
Actual commit that I missed in #1384 
=> Update Release Drafter details and documentation

README.md
=> community communication highlight on readme

RELEASE.md
Let's try using a `next-release` branch for docs.
Also split the super-long lines into paragraphs for ease of diff viewing
and reading, add some markup here and there, fix some typos and reword a
couple of unclear sentences.
=> Document how docs are handled before and during release.

keps/20200225-reading-parameter-values-from-a-file.md
This KEP describes an alternative way to provide parameter values when installing or
updating an operator instance.
=> KEP-26: Reading parameter values from a file

keps/0020-manual-plan-execution.md, keps/README.md
=> Update KEP-20 status

pkg/engine/resource/object_key.go
As caching is hard, using a cache for the discovery interface needs more discussion and work.
This PR improves the lookup a bit by only fetching the specific groupVersion that we need to check, not all serverGroupsAndResources.
Relates to #1421 #1422 
=> Fetch only server resources for a specific groupVersion

.goreleaser.yml, go.mod, go.sum
bump to kuttl 0.2.1 release and adding darwin back to release for local testing
=> KUTTL 0.2.1 Bump for Release

.goreleaser.yml
=> Remove 32-bit Darwin from Release

pkg/kudoctl/kudoinit/prereq/webhook.go
=> Use correct APIGroup for webhook cert-manager annotation

.github/workflows/release-drafter.yml
=> github releaser-draft update

keps/0029-operator-dependencies.md, keps/README.md
=> Updated KEP list

test/e2e/plan-trigger/00-assert.yaml, test/e2e/plan-trigger/01-assert.yaml, test/e2e/plan-trigger/01-install.yaml, test/e2e/plan-trigger/02-assert.yaml, test/e2e/plan-trigger/02-trigger.yaml, test/e2e/plan-trigger/feature-operator/operator.yaml, test/e2e/plan-trigger/feature-operator/params.yaml, test/e2e/plan-trigger/feature-operator/templates/configmap.yaml
=> Add an e2e test for `kudo plan trigger` command

pkg/kudoctl/cmd/init.go
This changed was introduced in this PR: https://github.com/kudobuilder/kudo/pull/1505/files#diff-c74faa6263971005d609e60d78ff0f8eL162
Signed-off-by: Alena Varkockova <avarkockova@mesosphere.com>
=> Nit: Update comments in kudo init

pkg/kudoctl/cmd/install.go, pkg/kudoctl/cmd/root.go
Follow-up to https://github.com/kudobuilder/kudo/pull/1579
=> Clarify `kudo install` examples.

.circleci/config.yml, test/Dockerfile
=> Run the upgrade tests as part of a PR

README.md
The community meeting is scheduled _Every 2 weeks on Thursday_.
Signed-off-by: Matthias Eichstedt <matthias.eichstedt@d2iq.com>
=> Correct schedule for community meeting

pkg/kudoctl/cmd/output/output.go, pkg/kudoctl/cmd/root.go, pkg/kudoctl/cmd/version.go
=> Add JSON/YAML output for kudo version

hack/generate_krew.sh
The template used in https://github.com/kubernetes-sigs/krew-index is different from the one created here. As there's additional checks for the generated 'kudo.yaml' in the krew-index project, we should consider that version canonical. The template has been updated accordingly.
=> Update krew template to reflect what's in krew-index

keps/0032-community-repository-management.md
The [operators-index](https://github.com/kudobuilder/operators-index) project implements what was proposed in the KEP.
=> KEP-32: Change status of KEP-32 to 'implemented'

pkg/kudoctl/kudoinit/crd/crds.go, pkg/kudoctl/util/kudo/kudo.go
Two changes that slipped through between merges
=> Fix changes in main branch

pkg/kudoctl/resources/dependencies/resolve_test.go
=> Fix a broken function call in 'resolve_test.go'

.golangci.yml, pkg/engine/renderer/enhancer_test.go, pkg/kudoctl/cmd/plan/plan_status_test.go, pkg/kudoctl/packages/verifier/template/verify_render_test.go
gofmt required code updates to resolve
=> Adding a number of additional linters 

.github/CODEOWNERS
=> Remove myself from 'CODEOWNERS'

pkg/webhook/instance_admission.go, test/upgrade/cert-manager-detection/06-install-kudo.yaml
Backport of nil map bug for parameters
=> Fixes nil map bug on creation BackPort

cmd/manager/main.go, test/run_tests.sh
Add old v1beta1 extension api so health check works correctly
=> Fix flaky integration test

RELEASE.md
Signed-off-by: Rishabh Bohra <rishabhbohra01@gmail.com>
=> Fix broken links in the Release docs

test/upgrade/upgrade-to-current/00-install-old-kudo.yaml
While installing older version of kudo in the upgrade test, use wait flag to ensure the controller is fully up and running.
=> Use --wait flag while installing old kudo

hack/generate_krew.sh
add arm64 metadata to krew, to allow for darwin arm64 install via krew.
Fixes #
=> add arm64 to krew
